### ISSUE TITLE
[MAYA-121225] Performance issue when lots of models are selected

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1991] opened 2022-01-18 19:02 UTC
**Describe the bug**
When testing the performance of common set dresser workflows, we noticed that there is a very big slowdown when the user has the root of a heavy city set selected (or similarly, a group that contains lots of models). The set has thousands of models with varying complexity (hero buildings, hero props, etc). Unfortunately, the set we used to test is a production asset so I cannot share it to include steps to reproduce. 

We noticed that it typically takes ~10 seconds to perform common actions with a city set selected.
- Selecting/de-selecting the root in the outliner
- De-selecting in the viewport
- Rotating, panning, or zooming the camera (per update)
- Translating the set (per update)
- Framing the set ('F')

Since it takes so long to perform each update when moving the camera or translating the set, it is not interactive and feels unresponsive.

It also seems to take a very long time to switch between the channel box and attribute editor with the set selected (~ 25-30 seconds).

Thank you!

**Specs (if applicable):**
maya2022.update3

**Comment by williamkrick** [comment] 2022-01-18 20:30
Hi @gracekumagai,

I logged MAYA-121225 to track this one. I'm testing with a heavy scene internally which takes me ~3s to select the root in the outliner. I'm guessing that the bottlenecks you are seeing are similar to the ones I am, but without a sharable scene I can't be sure. I think my test is similar enough, but the possibility of a significant difference exists.

With that said, I'm reproducing slowness with workflows 1, 2, and 4.

With workflow 3 and 5 it is less clear. With 3 (Rotating, panning or zooming the camera) the first couple frames are slow, but then consolidated world kicks in and the subsequent frames are fast. Similarly, when consolidated world is working the framing the set is slow.

One difference between our scenes could be materials. VP2 render delegate has the ability to consolidate objects whose material compiles to the same shader if the only difference in the material parameters is the diffuseColor. If your materials compile to different shaders, or you have more parameters on your materials that vary from object to object then consolidated world doesn't work and VP2RenderDelegate's performance suffers. Can you share some more details about the materials you are using in the slow scene and how they vary from prim to prim?

What is happening here is modifying the selection is changing the consolidation status of the MRenderItems that VP2RenderDelegate uses to draw the wireframe objects. After a few frames those objects get consolidated and the performance jumps. That explains the bad performance translating the set as well. Setting the transform breaks the MRenderItems out of consolidation and triggers the slower drawing path.

Can you verify that when consolidated world is enabled you do see better performance rotating, panning or zooming the camera after 5 or 10 frames? If you do have a lot of material variation and interesting test would be for you to remove the material assignment from each rprim and see what the performance is like. You can also try enabling "use default material" in the viewport. Use default material should enable the fast consolidated world performance no matter way your material variation is like, and that should allow workflow 3 and 5 to be fast.

**Comment by williamkrick** [comment] 2022-01-27 13:28
I traced the performance problem back to a workaround I did for a USD issue.

The USD issue: https://github.com/PixarAnimationStudios/USD/issues/1516
The workaround: https://github.com/Autodesk/maya-usd/pull/1897

The plan now is to temporarily disable the workaround https://github.com/Autodesk/maya-usd/pull/2034, until MayaUSD is shipping with USD that has a fix for the underlying issue. I'm going to create a PR for the proposed `HdChangeTracker::GetInstanceIndicesChangeCount`.

**Comment by williamkrick** [comment] 2022-02-03 15:57
All the changes I have planned for this one are now up on github, with #2058 still to be merged.

With all of these changes I think the scene navigation workflows will all be fast (framing the camera, manipulating the camera, switching between AE and channel box). Any editing workflows will be slower. The changes I made improve selection and de-selecting performance a little, but I don't think any of the changes improve the performance of workflow 4 translating the set.

@gracekumagai can you try out the latest changes and let us know what you're still finding slow and how critical the performance of those slow operations is for you? The regression where manipulating the camera was slow was definitely high priority, but I'm not sure of the importance of translating the full set.

**Comment by santosg87** [comment] 2022-05-02 17:58
@gracekumagai closing this one for now, as the work needed seems to be all done. please feel free to re-open if the issue is still persisting for you guys! :)

**Closed by santosg87** 2022-05-02 17:58 UTC
Labels: bug
