### ISSUE TITLE
[MAYA-112773] Duplicating a model should bring it in loaded

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#1542] opened 2021-07-02 23:09 UTC
Our users noticed that when duplicating a model by Ctrl+D in the Outliner, the new model brought into the scene unloaded. They would prefer to have them loaded.

After discussions with Will & Krystian we suspect this is just a bug.

**Comment by wtelford** [comment] 2021-07-06 19:35
@santosg87 Please log internally if you can reproduce this.

**Comment by santosg87** [comment] 2021-07-20 14:45
hi @dj-mcg i am having trouble reproducing this. i have tried a few different instances and workflows, but when i duplicate, i always get my models loaded. would you be able to add a bit more details on the behavior they are seeing? are they duplicating prims that are not loaded to begin with? are the unloaded prims still visible?

**Comment by dj-mcg** [comment] 2021-07-20 16:30
Hi @santosg87 - I just tried creating a stage on a new layer, adding a prim, and duplicating. Sure enough, this comes in loaded. It must be specific to duplicating referenced models. Let me try to collect more details surrounding the issue.

It's also worth noting I'm testing this in base Maya 2022, so if there have been any fixes only available in PRs, I haven't picked those up. I've been waiting for folks to iron out licensing issues but it seems like I should just circumvent all of that and set up a local install.

**Comment by dj-mcg** [comment] 2021-07-27 21:24
As far as I can tell, the model/prim you are duplicating must have a payload (ie. can be loaded/unloaded) and must be parented under an Xform prim. The duplicated model will come loaded only if you've already done "Load with Descendants" on the parent. The load state of the source model won't matter - you can duplicate an unloaded prim, and if the parent has been loaded w/ descendants, the duplicated model comes in loaded.

If you don't "Load With Descendants" on the parent prim, and instead only "Load" the source model itself, the duplicated model will come in unloaded.

**Comment by wtelford** [comment] 2021-09-29 19:29
Hey @dj-mcg,
I'd like to clarify your comment "The expectation of our users is that the duplicated model always comes in loaded."

My thought is:
When duplicating a prim, the duplicated prim should have the same load state as the source prim we are duplicating, not always be loaded, correct?

If source is unloaded, the duplicate should be unloaded.
If source is loaded, then the duplicate should be loaded. (regardless of ancestor load state)

If I'm an artist who has unloaded a prim because it is too heavy, I wouldn't want to take the hit for loading that object just because I duplicated it, but if I am working with a prim that is already loaded and I duplicate it, I would fully expect to see that prim to be loaded as well.

**Comment by dj-mcg** [comment] 2021-09-29 19:44
That sounds right to me, @wtelford  - thanks for clarifying!

**Comment by gracekumagai** [comment] 2021-11-23 20:35
This seems to be working as expected now - thank you for the fix!

**Comment by santosg87** [comment] 2022-01-10 17:51
Marking this as closed based on the above comment :)

**Closed by santosg87** 2022-01-10 17:51 UTC
Labels: bug, composition arc
