### ISSUE TITLE
Can't load published plugin (release 0.1.0)

### ISSUE THREAD

**Issue by Allottho** [Autodesk/maya-usd#448] opened 2020-04-20 18:29 UTC
Hi! I'm having trouble with loading plugin from the published release build: https://github.com/Autodesk/maya-usd/releases/tag/v0.1.0
After following the instructions provided in the txt file, I see this list of available plugins:
![PluginList](https://user-images.githubusercontent.com/28146743/79783958-2fbdae00-834a-11ea-8814-f1f3499265ff.PNG)
First, am I correct, that there should be more on this list?
Second, attempt to activate mtoh or mayaUsdPlugin I get this message:

> // Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : C:/Users/MyName/Documents/maya/2020/plug-ins/MayaUSD/plugin/adsk/plugin/mayaUsdPlugin.mll
> The specified procedure could not be found.
> // Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : C:/Users/MyName/Documents/maya/2020/plug-ins/MayaUSD/lib/maya/mtoh.mll
> The specified procedure could not be found.

This was checked on 2 PCs, one of them with a clean Maya2020 installation.
I do not have any python environment on this PC or any compilation tools.

Interesting note, that trying to understand what can be done, I've found some environment variables I may need to set (for example, MAYA_MODULE_PATH, pythonpath and path). However, setting pythonpath and path didn't change anything, and setting module path (to modules folder in 2020) actually prevented Maya from displaying the plugin in the plugin list. I was able to return the plugins to the list only after I've deleted module path variable and restarted PC.

**Steps to reproduce**
1. Download the published binary release https://github.com/Autodesk/maya-usd/releases/tag/v0.1.0
2. Follow the instructions from txt file
3. Start Maya and go to the plugin editor
4. Locate mtoh or mayaUsdPlugin and try to activate it
5. See error message. Plugin remains inactive

**Expected behavior**
According to published installation instructions coming with the plugin, user should be able to activate the plugin without any additional actions.

**Specs (if applicable):**
 - Windows 10 (1903)
 - Binary release v.0.1.0 00d651a
 - Maya2020

**Comment by santosg87** [comment] 2020-04-20 18:49
Hi ther @Allottho thanks for logging this.

Regarding the first issue, that is expected. we have compiled mayaUsd which is the main plugin we are working on a daily basis and developing currently. The other plugins would need to be compiled locally. :)

Regarding the second issue you are running into - based on the image and the error you are seeing, there are two possibilities:
1. there could be a typo on the path to the USD folder, which mayaUsd looks for when loading.
2. the language on your system could be causing a bug here. We would need to investigate a bit further. :)

**Comment by Allottho** [comment] 2020-04-20 19:00
Thank you!
Okay, I see. As I'm not a developer, I'll ask a colleague to help me out with the build.
This path to the USD folder, it's not user-set, right?
About the language - it is possible, that cyrillic is affecting it, but the other PC I've tried this on didn't have any unusual symbols in the paths, and OS language is english, yet behavior was the same.

**Comment by santosg87** [comment] 2020-04-20 19:39
the USD path would be set by the user - as those folders aren't there by default.
you should have something like this in the end:
USD path:
 C:/Users/MyName/Documents/maya/2020/bin/USD (here you should see "bin", "lib" and "plugin")
mayaUSD path:
C:/Users/MyName/Documents/maya/2020/plug-ins/MayaUSD (here you shoudl have "include" "lib" "plugin" and a file called "Build_info.txt" )
module:
to dynamically load : C:/Users/MyName/Documents/maya/2020/modules (here you should have the mayaUSD,mod file)

I also noticed you have onedrive set for your documents. I will try to ahve the same setup on my side and see if i can reproduce your problem. :)

Cheers!

**Comment by Allottho** [comment] 2020-04-20 20:21
Thank you! Ah, yes, so those are the paths from the txt file, got it.
Looks like paths are correct so far.
Yes, one of the PCs (one with cyrillics) does have the onedrive active, so that could add problems as well.

**Comment by Allottho** [comment] 2020-04-21 18:31
Okay, this is interesting. So, looks like you actually have to set lib and bin paths into the path variable.
Not sure why it didn't work first time, probably something was wrong.
Anyway, I think this should be added to the installation instruction, maybe? Or eventually this will be handled automatically?

**Comment by santosg87** [comment] 2020-04-23 14:06
interesting. does the mod file not include those paths for you? generally, the mod file in the documents folder should handle everything. would you be able to share the mayaUSD.mod? 

thanks for logging this!

**Comment by Allottho** [comment] 2020-04-23 14:15
Here it is:

+ USD 0.20.2 ../bin/USD
PYTHONPATH+:=lib/python
PATH+:=bin
PATH+:=lib

+ MayaUSD_LIB 0.1.0 ../plug-ins/MayaUSD
PATH+:=lib
PYTHONPATH+:=lib/python
PXR_PLUGINPATH_NAME+:=lib/usd
VP2_RENDER_DELEGATE_PROXY=1

+ MayaUSD 0.1.0 ../plug-ins/MayaUSD/plugin/adsk
MAYA_PLUG_IN_PATH+:=plugin

+ MTOH 0.1.0 ../plug-ins/MayaUSD/lib
MAYA_PLUG_IN_PATH+:=maya

**Comment by delattj** [comment] 2020-07-22 18:09
I do reproduce the issue on my side too.
My OS is Windows 10 (English).
For me too, I had to add the USD SDK (0.20.2) lib and bin folder to my path in order to fix the issue.

**Comment by delattj** [comment] 2020-07-22 18:43
I got it fixed also with this mod file:
`+ MayaUSD_LIB 0.1.0 ../plug-ins/MayaUSD
PATH+:=lib
PYTHONPATH+:=lib/python
PXR_PLUGINPATH_NAME+:=lib/usd
VP2_RENDER_DELEGATE_PROXY=1
PYTHONPATH+:=../../bin/USD/lib/python
PATH+:=../../bin/USD/bin
PATH+:=../../bin/USD/lib

+ MayaUSD 0.1.0 ../plug-ins/MayaUSD/plugin/adsk
MAYA_PLUG_IN_PATH+:=plugin

+ MTOH 0.1.0 ../plug-ins/MayaUSD/lib
MAYA_PLUG_IN_PATH+:=maya
`

**Comment by kxl-adsk** [comment] 2020-08-03 13:28
We posted new binaries for v0.2.0 with an installer (https://github.com/Autodesk/maya-usd/releases/tag/v0.2.0). Please use the instructions available in the readme and we are hoping installation will be much easier now. Let us know!

**Comment by kxl-adsk** [comment] 2020-11-06 18:27
Closing for now since we are now at release 0.5.0. Next time please start a new GitHub discussion so we can narrow down the cause and identify the issue to fix.

**Closed by kxl-adsk** 2020-11-06 18:27 UTC
Labels: bug
