### ISSUE TITLE
Selection of a ProxyShape will select individual prims in the hierarchy in VP2.0

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#262] opened 2020-02-07 23:13 UTC
**Describe the bug**
When selecting a ProxyShape object in Viewport 2.0, a subset of prims in the ProxyShape hierarchy are often selected rather than the entire ProxyShape itself. While there may be workflows where this behavior is helpful, the default behavior should be that the entire Proxy Shape is selected.

**Steps to reproduce**
1. Run the testPorxyShapeSelectionPerformance test. Observe the failed assert

**Expected behavior**
The test passes with no errors.

**Additional context**
This test is part of a suite of tests that are run internally at Pixar. They are not included run as part of the external Pixar usdMaya plugin tests since they are making assumptions about the runtime environment that may not be valid for all users. However, moving forward, these tests should be run internally within Autodesk to validate correctness when testing any changes or fixes to the usdMaya plugin.

**Comment by kxl-adsk** [comment] 2020-02-18 19:50
The described bug is actually expected behavior. We enable native workflows on USD data and selection is the foundation for many of them.

It sounds like for your workflows, you would like to have control over selection behavior, i.e USD prim vs DG Shape.

**Comment by kxl-adsk** [comment] 2020-03-02 18:30
@mattyjams assigned this issue to you since you have open PR for it.

**Comment by santosg87** [comment] 2020-03-23 20:49
Hi @dj-mcg can this one be closed, since the PR was merged on #315

**Comment by dj-mcg** [comment] 2020-03-23 20:58
I'm fine with it as long as @mattyjams <https://github.com/mattyjams> approves
- thanks!

**Comment by mattyjams** [comment] 2020-03-23 21:07
Yup, we addressed this with the changes in #315. Ok to close, thanks @santosg87!

**Closed** 2020-03-23 21:32 UTC
Labels: bug, vp2renderdelegate
