### ISSUE TITLE
[MAYA-124789] Export of bezierCurve type Curves is Incorrect

### ISSUE THREAD

**Issue by michaeljefferies** [Autodesk/maya-usd#2518] opened 2022-08-01 21:42 UTC
The code in nurbsCurveWriter.cpp incorrectly assumes that if the typeName of the curve is "bezierCurve" that the curve will be compatible with UsdGeomBasisCurves.  However this is not the case.  The actual test should be based on the degree, weights and knot vector being compatible with the various combinations for UsdGeomBasisCurves attributes type, basis and wrap.

While it may be the case that using the interactive Bezier curve tool will always yield a curve compatible with UsdGeomBasisCurves, it is possible to construct a curve with a typeName of "bezierCurve" that is not a bezier basis curve.  For example the command:
curve -bezier -d 3 -p 0 0 0 -p 1 1 0 -p 2 1 0 -p 3 0 0 -k 0 -k 1 -k 2 -k 3 -k 4 -k 5;

This command will generate a curve with a typeName of "bezierCurve", but the curve is not a bezier basis curve because the knot vector doesn't have bezier knots of (0, 0, 0, 1, 1, 1).  Therefore it cannot be represented with a UsdGeomBasisCurves prim.

Note that this is also the case with a degree other than 3 (cubic) even when the knot vector is a bezier knot vector. For example the command:
curve -bezier -d 4 -p 0 0 0 -p 1 1 0 -p 2 1 0 -p 3 0 0 -p 4 1 0 -k 0 -k 0 -k 0 -k 0 -k 1 -k 1 -k 1 -k 1;

This command will generate a curve with a typeName of "bezierCurve", and indeed it is a bezier curve, but it is not cubic.  Therefore it cannot be represented with a UsdGeomBasisCurve prim.

1. Create a bezier curve with a uniform knot vector. e.g. "curve -bezier -d 3 -p 0 0 0 -p 1 1 0 -p 2 1 0 -p 3 0 0 -k 0 -k 1 -k 2 -k 3 -k 4 -k 5;"
2. Export the curve to usd
3. Check the file and notice that is written out as UsdGeomBasisCurves with the points of the curve.
4. View the curve in a usd viewer and notice that it doesn't match the original curve in maya.

**Expected behavior**
If a curve cannot be represented by a UsdGeomBasisCurves prim, it should be exported as a UsdGeomNurbsCurves prim.

**Comment by santosd** [comment] 2022-08-08 18:44
Hello @michaeljefferies, thank you for reporting this issue, I have tested it on my end and was able to reproduce the problem. I have opened a ticket internally MAYA-124789 so that we look into a resolution.

**Comment by santosd** [comment] 2023-01-27 21:34
Hello @michaeljefferies, this issue was recently fixed by this https://github.com/Autodesk/maya-usd/pull/2820 if you would like you can build from the latest and can test the fix. I tested it on my end and I seem to be getting the expected outcome. The Export\Import support is all there. However, when creating a stage from this file we still don't see the curve like the original because the support to view these types of curves is not there yet. If you are unable to build your own plugin, then the next one we ship should have the fix in it for you to try out. I am going to be closing this ticket out for now, but if you come across anything when you test, please let us know and I can reopen the ticket.

**Closed by santosd** 2023-01-27 21:34 UTC
Labels: bug, reproduced
