### ISSUE TITLE
Maintain current edit target for duplicated proxy nodes

### ISSUE THREAD

**Issue by msercheli** [Autodesk/maya-usd#1770] opened 2021-10-18 19:29 UTC
**Describe the bug**
When an existing proxy node (which has the session layer as active edit layer) is duplicated, the newly created proxy node has the root layer as the active edit layer. To be a true duplication, shouldn't the duplicated one maintain the user-selected edit target layer?

**Steps to reproduce**
1. Create a new proxy node
2. Using the Layer Editor, make the session layer active
3. With the proxy node (transform node) selected, hit Ctrl+d (duplicate it)
4. From the Layer Editor, verify that the root layer is active in the newly duplicated proxy node

**Expected behavior**
The newly duplicated proxy node maintain the user choice of which layer is active.

**Attachments**
N/A

**Specs (if applicable):**
 - Linux CentOs 7
 - gcc 6.3.1
 - Maya 2022
 - Github tag: v0.12.0

**Additional context**

**Comment by santosg87** [comment] 2021-11-01 19:33
@msercheli not sure i am seeing the same behavior mentioned. I do see the active stage changing when duplicating the proxy, but the target layer remains the session layer.

![DuplicateProxy](https://user-images.githubusercontent.com/3026529/139730280-b606d393-ad10-4147-b804-30a7d4a2e7f2.gif)


the active stage changing, to me, seems like the expected behavior, as you are duplicating and creating a new stage.
am i missing something here?

**Comment by msercheli** [comment] 2021-11-01 21:19
Interesting George.
Thanks for the demo/video above. That is the right behavior.

Are you using the plugin built from tag 0.12.0? (Although I observed the same behavior in tag 0.13.0 as well).
Maybe it's fixed in the build you are using. Could you share the tag your build is coming from? Also, are you using Maya 2022.0 or 2022.2 (or newer)?

Thanks.

**Comment by santosg87** [comment] 2021-11-08 18:06
hi @msercheli I have tried this on a few different combos (0.11.0 to 0.13.0 + Maya 2022 to 2022.2) as well as multiple platforms (tried a few variations on MacOS, Linux and windows). they all seemed to behave the same on my testing. I am using the release tags to test. :)

I will try a couple more things to see if i can get my set up on a similar state to you. If you try it with fresh Maya Preferences, does the behavior still show up?

cheers!

**Comment by msercheli** [comment] 2021-11-17 18:35
Hi George,

I think I was able to identify the issue.
I am flipping an optionVar in my userSetup.py upon Maya startup:
    cmds.optionVar(intValue=("mayaUsd_ProxyTargetsSessionLayerOnOpen", 1))

You can run this optionVar from the Script Editor (Python) before creating a new proxy node.
This optionVar causes the "sessionLayer" to be selected and active when a proxy node is created pointing to a USD file on disk. Meaning, "**_if a proxy is created from file, select the session layer automatically._**"
Now, I do that for some internal pipeline reasons that are not pertinent to this conversation.

Since the "session layer" was made active by optionVar, when I duplicate that proxy node, it **doesn't** preserve the session layer as active in the duplicated proxy.

If I make the "session layer" active manually (through UI), all works fine as you demonstrated.

I hope that helps pin-point the issue.

**Comment by santosg87** [comment] 2022-01-17 18:08
Thanks for the info Marcelo! 

I am able to reproduce your case on our side as well. it seems to be indeed related to how you are targetting the session layer here. I will investigate this a bit more and log an internal issue as needed. 

thank you!

**Comment by santosg87** [comment] 2024-09-16 17:27
retesting this on more recent MayaUSD+Maya builds, and i am not seeing the problem anymore. we have made several improvements to our layer editor workflows, so this might have been fixed without specific code targeting this issue. :)

marking this issue as closed for the time being. if this is still an issue, feel free to re-open, or log a new ticket!

**Closed by santosg87** 2024-09-16 17:27 UTC
Labels: bug, proxy, reproduced
