### ISSUE TITLE
Support for point based drawing in Viewport 2.0

### ISSUE THREAD

**Issue by radon199** [Autodesk/maya-usd#1452] opened 2021-06-02 17:07 UTC
**Is your feature request related to a problem? Please describe.**
We use point clouds in USD for FX, and like to be able to allow layout to time offset canned FX elements. This is something we can do through Storm but are unable to do in Viewport2.0 as it does not support drawing points, making it impossible to visualize the effect or the time offsets. Only mesh and curve Rprim types appear to be supported by the render delegate.

**Describe the solution you'd like**
Support in Viewport2.0 for drawing point based Rprims so that we can use these built in Usd types.

**Describe alternatives you've considered**
We have authored proxy meshes that are meshed versions of the point clouds however this requires extra work to setup in the pipeline vs just drawing the point cloud.

**Additional context**
Maya-2020
maya_usd-0.9.0

**Comment by wtelford** [comment] 2021-06-04 17:17
@santosg87 can you please log this internally.

**Comment by radon199** [comment] 2021-06-21 20:42
Yes, sorry for the duplicate, it is the same request.

**Comment by wtelford** [comment] 2021-07-12 20:14
Great, we'll close this as a duplicate of #487

**Closed by wtelford** 2021-07-12 20:14 UTC
Labels: enhancement, vp2renderdelegate
