### ISSUE TITLE
Maya 2023 crashes when exporting aiAreaLight node

### ISSUE THREAD

**Issue by oumad** [Autodesk/maya-usd#2351] opened 2022-05-12 14:59 UTC
**Describe the bug**
Maya 2023 crashes when attempting to export objects that include an aiAreaLight with USD Export

**Steps to reproduce**
1. Start a new scene in maya 2023
2. Create an aiAreaLight (Arnold > Lights > Area Light)
3. Select the light in viewport or outliner
4. Go to file > Export Selected, choose USD Export, and click export.

**Expected behavior**
A USD file to be exported without scene crash when the selection includes aiAreaLight objects

**Attachments**
I included a maya scene file that contains an area light which causes a crash when I export selected.
[area_light.zip](https://github.com/Autodesk/maya-usd/files/8680258/area_light.zip)

**Specs (if applicable):**
 - OS : Windows 10
 - Maya version : Maya 2023
 - Maya USD version : tested on both 0.17.0 and 0.18.0 releases.

**Additional context**
The crash doesn't happen in maya 2022 or 2020 with the same maya-usd release.

**Comment by santosg87** [comment] 2022-07-04 17:58
this seems to be a duplicate of #2341. Closing this issue for now, so we can track the work done through that issue. :)

**Comment by santosg87** [comment] 2022-07-06 20:56
after a bit more investigation, it seems this issue is indeed unique. re-opening this.

@oumad - just a question regarding your current export settings:
- are you using any specific plugin configuration?
- do you have a parent scope set?
- if you try using the command line (something like ```
from maya import cmds; 
cmds.file(exportAll=True, type='USD Export')
``` does it still crash?

**Closed** 2022-07-07 18:33 UTC
Labels: bug
