### ISSUE TITLE
Bug when deselecting a stage item.

### ISSUE THREAD

**Issue by ChokmahBinah** [Autodesk/maya-usd#596] opened 2020-06-18 19:31 UTC
**Describe the bug**
Selection highlighting don't update when deselecting any stage item after selecting it.
The selection highlighting desactivated only after rotating the perp view.
(The problem occurs using mtoh or Viewport 2.0)

**Steps to reproduce**
1 - Load a stage.
2 - Select any item from the stage.
3 - Deselect it.
4 - Rotate View.

**Expected behavior**
Selection highlighting should be desactivated on selected items when deselecting them.

**Attachments**
![mToH_deselection_bug](https://user-images.githubusercontent.com/33164632/85063616-af30f780-b1aa-11ea-8221-3e8bd6fa7d93.gif)

**Specs (if applicable):**
 - Windows 10
 - Visual Studio 2017
 - Maya 2020
 - dev at 3a331444f
 - dev at 205cb1a8d

**Additional context**
Tested using Python 2.7.14 for Pixar USD and Maya USD

**Comment by santosd** [comment] 2020-11-06 19:21
Hi @ChokmahBinah ,
Thank you for reporting this. I gave it a try using Maya 2020.3 and [the latest release](https://github.com/Autodesk/maya-usd/releases/tag/v0.5.0) and was not able to reproduce this issue. I do remember this being an issue at one point but has since been resolved.
![2020 3_deselection](https://user-images.githubusercontent.com/29235905/98406060-494eea80-203b-11eb-89a9-0ca6d9c818c0.gif)

**Comment by santosd** [comment] 2020-11-06 19:49
Going to close this issue out for the time being. However, @ChokmahBinah if you find that the issue is still happening for you in the latest release let me know and we can reopen.

**Closed by santosd** 2020-11-06 19:49 UTC
Labels: bug

**Comment by ChokmahBinah** [comment] 2020-11-06 20:33
I’ll do this for sure. I’ll test that this weekend 😉  Provenance : Courrier pour Windows 10 De : David SantosEnvoyé le :vendredi 6 novembre 2020 20:49À : Autodesk/maya-usdCc : ChokmahBinah; MentionObjet :Re: [Autodesk/maya-usd] Bug when deselecting a stage item. (#596) Closed #596.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ChokmahBinah** [comment] 2020-11-06 22:30
I just tested on the new version. The bug don't exist anymore ! 
Thank you a lot @santosd ;)

**Comment by santosd** [comment] 2020-11-09 17:13
That's great to hear! Thank you for verifying.
