### ISSUE TITLE
[MTOH] Maya is crashing when selecting keyed quick rig bones

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#1523] opened 2021-06-26 20:36 UTC
**Describe the bug**

**Steps to reproduce**
1. Bring in simple character
2. rig it with quick rig (human ik)
3. add key to the controls/bones
4. change viewport to mtoh
5. select one of the quick rig control bones
6. change the frame

**Attachments**
https://imgur.com/xS37vcI

**Specs (if applicable):**
 - Win 10 20H1
 - Maya 2020
 - maya-usd 0.10.0

**Comment by santosg87** [comment] 2021-06-28 19:59
@Xaia  we have seen some cases of Mtoh having trouble drawing geometry in maya with specific graphics cards. what is your system environment? do you get a crash with other maya geometry displaying on moth for you?

**Comment by Xaia** [comment] 2021-06-28 20:02
> 
> 
> @Xaia we have seen some cases of Mtoh having trouble drawing geometry in maya with specific graphics cards. what is your system environment? do you get a crash with other maya geometry displaying on moth for you?

I am running RTX 3090 with 471.11 drivers

**Comment by santosg87** [comment] 2024-09-16 15:36
I have re-tested this issue on a more recent maya build using MayaHydra, and could not reproduce this issue anymore. marking it as closed for the time being.

@Xaia feel free to re-open or create a new issue if this is still happening or your side!

**Closed by santosg87** 2024-09-16 15:36 UTC
Labels: bug, mtoh
