### ISSUE TITLE
[MAYA-114855] Crash when interacting with outliner after unloading payload

### ISSUE THREAD

**Issue by eddiehoyle** [Autodesk/maya-usd#1688] opened 2021-09-07 17:53 UTC
**Describe the bug**
Maya crashes if user interacts with USD hierarchy in Maya's outliner if a prim with payloads is unloaded while expanded.

**Steps to reproduce**

**Note:** This repro has been manually copied and typed out (internal network restrictions, sorry) and is untested.

1. Save these layers to disk in the same folder:
   ```
   // entry.usda
   #usda 1.0
   (
       defaultPrim = "entry"
   )
   def "entry" (
       kind = "component"
       append payload = @./payload.usda@</entry>
   ) {}
   ```
   ```
   // payload.usda
   #usda 1.0
   over "entry" {
       def Cube "cube" {
       }
   }
   ```
2. In Maya, create proxy from file "entry.usda" with payloads enabled and expand the outliner hierarchy. You should see the following:
   ```
   proxy             # transform
       shape         # shape
           entry     # /entry
               cube  # /entry/cube
   ```
3. Unload payload prim
   ```python
   import mayaUsd
   from maya import cmds
   stage = mayaUsd.ufe.getStage("|world{}".format(cmds.ls(type="mayaUsdProxyShape", long=True)[0]))
   entry = stage.GetPrimAtPath("/entry")
   entry.Unload()
   ```
4. Try to select, or collapse USD hierarchy in Maya outliner
5. *crash*

Error message:
```
maya.bin crashed. FATAL ERROR: Used expired 'Cube' prim </entry/cube>
```

If the hierarchy is collapsed before calling `Unload`, no crash occurs. My guess the outliner needs to be refreshed.

**Expected behavior**
The outliner should refresh, display the correct USD structure (payload pruned) and should not crash.

**Specs:**
- Centos 7
- gcc 6.3.1
- Maya 2020
- Maya USD 0.10.0
- Usd 20.11

**Comment by santosg87** [comment] 2021-10-04 17:22
@eddiehoyle I am trying to reproduce this one for a bit of time now, but no luck. 

this seems to behave as expected on my side. are you able to test this on the latest mayaUSD build to confirm?

**Comment by santosg87** [comment] 2021-11-01 20:25
@eddiehoyle thanks for the info! this seems to be indeed something specific to 2020 only. I am able to repro this on 2020.4, but not on 2022 builds. 

given that this is something specific to 2020, my guess is that there is some UFE support missing in there.

**Comment by santosg87** [comment] 2022-02-24 10:48
@eddiehoyle we have a fix for this issue merged now. are you able to test and confirm?

**Comment by eddiehoyle** [comment] 2022-02-24 19:51
Hi @santosg87, I've since moved to another company so don't have access to the tickets original environment for testing. I'll follow up here if I run into this issue again. Thanks for taking a look!

**Comment by santosg87** [comment] 2024-09-16 17:16
closing this one for now, as we haven't had any new reports of this issue.

**Closed by santosg87** 2024-09-16 17:16 UTC
Labels: bug, proxy, reproduced, outliner, crash
