### ISSUE TITLE
handle stage's up-axis more accurate

### ISSUE THREAD

**Issue by egorchatsperasoft** [Autodesk/maya-usd#2232] opened 2022-03-31 14:51 UTC
**Is your feature request related to a problem? Please describe.**
Let it be handled correctly which axis is up - during load or export stage. As a stage-shape parameter, for example.

**Comment by santosd** [comment] 2022-05-16 17:25
Yes logged internally as https://jira.autodesk.com/browse/MAYA-112588. This ticket is actually a duplicate of [GitHub #227 ](https://github.com/Autodesk/maya-usd/issues/227). I will go ahead and close this ticket since it is a duplicate.

**Closed by santosd** 2022-05-16 17:25 UTC
Labels: enhancement
