### ISSUE TITLE
Switching to Hydra crashes Maya instantly.

### ISSUE THREAD

**Issue by suekieza** [Autodesk/maya-usd#98] opened 2019-11-01 07:48 UTC
Hey there, 
Hydra plugin is loading on linux now(thanks @HamedSabri-adsk ), but when I try to switch the viewport to hydra it crashes instantly. 
Tested with a sphere(no textures), the barrel.usd asset, and nothing in the scene. Crashes every time. I can open the option box with the hydra settings, just can't switch to hydra. It doesn't through up any errors either just closes.

**Comment by BigRoy** [comment] 2019-11-01 08:58
@suekieza this sounds similar to this #68 which was fixed with #79 

> Fix the crash in mtoh due to inconsistent WANT_UFE_BUILD C++ macro definition across compilation units

It could be something different though. However, can you share your build log? Did it build with UFE enabled?

**Comment by suekieza** [comment] 2019-11-01 15:02
Hey there, here is my build log
[build_log.txt](https://github.com/Autodesk/maya-usd/files/3798418/build_log.txt)

I don't build with UFE enabled no (not as for as I know anyway)

**Comment by BigRoy** [comment] 2019-11-01 15:48
Your log states the following so it should be built with UFE:

> Building with UFE 1.0.0 features enabled.

It will automatically build with UFE if it can correctly find the Maya devkit during compiling, like it does in your build. 

Anyway, at this stage I'm not too sure what exactly is causing the issue. I'll leave it to someone else to see if they can help out.

**Comment by HamedSabri-adsk** [comment] 2019-11-01 18:35
@suekieza can you close this issue to avoid duplication and making it easier to track things?

You can directly add your comments in #68 . As for switching to Hydra GL, I was able to switch to Hydra after getting #79 fix. Do you have this fix already?

**Comment by suekieza** [comment] 2019-11-04 07:19
Shared my log up above. 
@BigRoy seems to think I should be on? What is the flag for the python build script and I will rebuild with it on, just to be sure.
Thanks

**Comment by BigRoy** [comment] 2019-11-04 08:52
> @BigRoy seems to think I should be on? 

Not necessarily. Did you build from the "fix PR" branch or did you pull the latest `refactoring_sandbox`? The latest `refactoring_sandbox` should indeed include that fix.

**Comment by suekieza** [comment] 2019-11-05 07:05
Will try rebuild today. Thanks @BigRoy

**Comment by suekieza** [comment] 2019-11-07 11:28
So I'm afraid even after rebuilding it today it still instant crashes.
[build_log.txt](https://github.com/Autodesk/maya-usd/files/3819335/build_log.txt)
Not sure what to do at this point. Do I add this as a new issue? @HamedSabri-adsk

**Comment by suekieza** [comment] 2019-11-18 12:41
Hello? I'm still stuck on this.

**Comment by HdC-adsk** [comment] 2019-11-18 15:47
Hi @suekieza ,

Hamed and I tried Windows and Linux and we couldn't reproduce. From the crash log, it looks different from #68. The top frame of Thread 0 is where MtoH calls into USD and nothing looks wrong at the first glance (but I am not familiar with MtoH). Since we cannot reproduce it, could you set a break point at HdMayaDelegateCtx ctor to see why it crashes when calling into `GetChangeTracker().AddCollection(TfToken("visible"))`?

**Comment by radon199** [comment] 2019-11-19 01:07
Just wanted to add I am getting the exact same crash as suekieza on CentOs-7.6

So far I have been unable to get the refactoring sandbox to draw anything.

**Comment by BigRoy** [comment] 2019-11-19 06:26
@radon199 Are you saying it doesn't work for you at all? Or are you solely referring to the `mtoh` plug-in and its Hydra (GL) viewport renderer as this issue described?

Either way, would you happen to have a build log and maybe even a crash log/dump to help investigate?

**Comment by suekieza** [comment] 2019-11-19 07:07
I will try @HdC-adsk suggestion and report back what I find.

**Comment by suekieza** [comment] 2019-11-19 09:56
I am also on Centos 7.....

**Comment by suekieza** [comment] 2019-11-19 14:09
Ok so I tried this all day with no success. I'm no C++ dev, I be but a humble python programmer here(also mostly houdini). 
[build_log.txt](https://github.com/Autodesk/maya-usd/files/3864133/build_log.txt)
[dumpdata.zip](https://github.com/Autodesk/maya-usd/files/3864123/dumpdata.zip)

**Comment by HdC-adsk** [comment] 2019-11-19 14:40
@radon199 Apart from this crash, mtoh is not the only rendering solution in the sandbox. Do you mean you cannot see anything from VP2RenderDelegate and AL proxy draw override either?

**Comment by HamedSabri-adsk** [comment] 2019-11-19 14:58
@suekieza 

I played around with switching to Mtoh from the refactoring_sandbox branch again today and still can't reproduce the crash on Linux. 

Do you have a step by step workflow that we can try? 

![Mtoh_screenshot](https://user-images.githubusercontent.com/48299423/69157182-9a747000-0ab2-11ea-896a-531802922dfc.jpeg)

**Comment by suekieza** [comment] 2019-11-19 15:40
Hey there,
Here's what I'm doing in maya:
[2019-11-19 17-36-06.flv.tar.gz](https://github.com/Autodesk/maya-usd/files/3864595/2019-11-19.17-36-06.flv.tar.gz)

Is there some thing else you guy's would like to see?

**Comment by HamedSabri-adsk** [comment] 2019-11-19 17:36
Just curious, what kind of graphic cards do you have?

**Comment by radon199** [comment] 2019-11-20 00:46
@BigRoy

Hey, After speaking with our developer our build is a couple weeks behind the last commit and as such I can't be sure if we are just on a fork with a bug.

I'll make a new issue if we have the same problem with the latest release.

**Comment by suekieza** [comment] 2019-11-20 07:03
@HamedSabri-adsk My computer stats....
![Screenshot from 2019-11-20 09-03-07](https://user-images.githubusercontent.com/53234220/69216304-8e50e700-0b74-11ea-88b5-3adbbe02653e.png)

**Comment by radon199** [comment] 2019-11-22 00:21
Hey,

So we built against the sandbox as of November 20th and still have all of the same issues as before.

CentOs-7 Nvidia GTX1080ti, Driver 390.77, usd-19.11, maya-2019.2.8774

When loading the plugin and creating a proxy via cmds.createNode, we set a path to a usdc file in the filepath attribute and nothing happens. No items are drawn in VP2.0 and no sub-components are displayed in the Outliner. The proxy will load the usd file as we get the proper bounding box information.

I can get the proxy to draw in VP2 by duplicating it. If I select any item in the outliner or in the viewport Maya will segfault with this stack trace : 
`*** Error in `/sw/packages/external/maya/2019.2.8774/platform-linux/arch-x86_64/os-CentOS-7/usr/autodesk/maya2019/bin/maya.bin': munmap_chunk(): invalid pointer: 0x00000000107463b0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7f5d4)[0x7f076804b5d4]
/sw/dev/rousselp/packages/usd/19.11.m1/platform-linux/arch-x86_64/os-CentOS-7/boost-1.61.0/python-2.7/pyside-2.0.0/ptex/qt_devel/lib/libhd.so(_ZNSt10_HashtableIN32pxrInternal_v0_19__pxrReserved__7SdfPathESt4pairIKS1_NS0_11HdSelection18PrimSelectionStateEESaIS6_ENSt8__detail10_Select1stESt8equal_toIS1_ENS1_4HashENS8_18_Mod_range_hashingENS8_20_Default_ranged_hashENS8_20_Prime_rehash_policyENS8_17_Hashtable_traitsILb1ELb0ELb1EEEE21_M_insert_unique_nodeEmmPNS8_10_Hash_nodeIS6_Lb1EEE+0xf1)[0x7f064a6ddc61]
/sw/dev/rousselp/packages/usd/19.11.m1/platform-linux/arch-x86_64/os-CentOS-7/boost-1.61.0/python-2.7/pyside-2.0.0/ptex/qt_devel/lib/libhd.so(_ZNSt8__detail9_Map_baseIN32pxrInternal_v0_19__pxrReserved__7SdfPathESt4pairIKS2_NS1_11HdSelection18PrimSelectionState`


Trying to switch to the GL renderer results in this error regardless of if there is a proxy created in Maya or not: 
`Stack trace:
pxrInternal_v0_19__pxrReserved__::HdChangeTracker::AddCollection(pxrInternal_v0_19__pxrReserved__::TfToken const&)
  pxrInternal_v0_19__pxrReserved__::HdMayaDelegateCtx::HdMayaDelegateCtx(pxrInternal_v0_19__pxrReserved__::HdMayaDelegate::InitData const&)
  pxrInternal_v0_19__pxrReserved__::HdMayaSceneDelegate::HdMayaSceneDelegate(pxrInternal_v0_19__pxrReserved__::HdMayaDelegate::InitData const&)
  void __gnu_cxx::new_allocator<pxrInternal_v0_19__pxrReserved__::HdMayaSceneDelegate>::construct<pxrInternal_v0_19__pxrReserved__::HdMayaSceneDelegate, pxrInternal_v0_19__pxrReserved__::HdMayaDelegate::InitData const&>(pxrInternal_v0_19__pxrReserved__::HdMayaSceneDelegate*, pxrInternal_v0_19__pxrReserved__::HdMayaDelegate::InitData const&)
  void std::allocator_traits<std::allocator<pxrInternal_v0_19__pxrReserved__::HdMayaSceneDelegate> >::construct<pxrInternal_v0_19__pxrReserved__::HdMayaSceneDelegate, pxrInternal_v0_19__pxrReserved__::HdMayaDelegate::InitData const&>(std::allocator<pxrInternal_v0_19_`

**Comment by suesauer** [comment] 2019-12-02 12:05
I have rebuilt today 1 December latest sandbox. Still crashes instantly when switching to hydra

**Comment by suesauer** [comment] 2019-12-03 14:21
Hey guy's, rebuilt again today. Latest USD pixar, Latest refactoring_sandbox and devtoolset-6 and this fixed the hydry crashing instantly on my side
![Screenshot from 2019-12-03 15-12-36](https://user-images.githubusercontent.com/58251706/70059138-e7932e80-15e8-11ea-8763-a8ada65c7cb5.png)

Hooray \:D/

**Closed** 2019-12-03 14:25 UTC
