### ISSUE TITLE
drawUfe plugin and maya_usd plugin, viewport slowdowns in Maya 2023

### ISSUE THREAD

**Issue by sanders3d** [Autodesk/maya-usd#3007] opened 2023-04-05 11:59 UTC
I just wanted to post this here also as one of our riggers has nailed down why Maya2023 is so slow when the maya usd plugin is loaded. We have tested this with maya_usd-0.20, maya_usd-0.22, maya_usd-0.23
Not sure if this is maya_usd related or not, but either way I would hope you devs can talk with each other :)

https://forums.autodesk.com/t5/maya-forum/drawufe-plugin-and-viewport-slowdowns-in-maya-2023/td-p/11870602

regards
stefan

**Comment by santosg87** [comment] 2023-04-05 18:58
Hi @sanders3d thank you for reporting this here! We will investigate a bit deeper, but from the general description on the forum discussion (awesome work narrowing things down! btw :) ) it does seem like this might be related to mayausd. I am a bit curious on the behavior here, since the rigs don't have any usd assets on them. we will look into it!

**Comment by sanders3d** [comment] 2023-04-06 05:05
Thank you, yeah the slowdown is quite a lot. And while we are not using USD as much as we would like, we are constantly testing it with sending geometry to the stage. And many of layouts are USD which then needs these plugins to be loaded.

**Comment by mdilena** [comment] 2023-04-06 09:28
Thanks for opening this issue here @sanders3d :) @santosg87 let me know if there's anything else I could do to help!

**Comment by mdilena** [comment] 2023-04-06 19:50
So, it looks like this is not an issue in Maya 2024. I just found some time to test it under the same scenario and the issue is gone, so my suspects on drawUfe.so might be correct? The version of libufe changed from 3 to 4 between the two maya releases, so maybe that's the reason why?

Hope this helps!

**Comment by mdilena** [comment] 2023-04-21 09:35
hey @santosg87 , thanks very much for confirming that! So it seems like it's a minimal disruption in the end, I wasn't exactly sure of what that Ufe thing was trying to draw in the viewport!

**Comment by santosg87** [comment] 2023-05-02 17:19
@mdilena given that this is a 2023 issue and there is a workaround, I am closing this for the time being, as we don't have planned work on this at this time. if planning changes for this, or the workaround proves not to be sufficient, feel free to reopen. :)

**Closed by santosg87** 2023-05-02 17:19 UTC
Labels: bug

**Comment by vincentgires** [comment] 2024-11-25 09:19
We have the same issue (on Windows only) with the current production version we use (0.28.0 and Maya 2024). Can we re-open this issue and provide a better solution for Windows users?

**Comment by vincentgires** [comment] 2024-11-25 09:48
And the workaround to only load mayaUsdPlugin without drawUfe does not help, it still makes the Maya interface with a lot of freeze.

**Comment by santosg87** [comment] 2024-11-25 16:33
@vincentgires if you are seeing this on 2024, it might be a different issue, as i don't think we could reproduce this behavior on that version of Maya. if you are able to add a couple of sample files as well, that would be very helpful in trying to narrow down the issue. 

I would recommend logging a new issue for this with your specific details, and we can investigate it. 

cheers!
