### ISSUE TITLE
[MAYA-104134] USDZ import not always working with 0.1 precompiled USD plugin

### ISSUE THREAD

**Issue by martin-pw** [Autodesk/maya-usd#394] opened 2020-03-30 21:40 UTC
I am having mixed results with usdz import using the 0.1 precompiled USD plugin.

usdc always works, usdz only sometimes works, depending on the workflow. Details:

**Windows**
 - Loading a usdc file via the File->Import menu works
 - Loading a usdz file via the File->Import menu works
 - Dragging a usdc file into the Maya viewport works
 - Dragging a usdz file into the Maya viewport does not work and generates an error: "Unrecognized file type".

**Linux**
- Importing a usdc file via python (cmds.file) into Maya batch works
- Importing a usdz file via python (cmds.file)into Maya batch does not work and generates this error:

    RuntimeError: No translator could be found to read the file 'filename.usdz'.
 

Maya 2020
Windows 10 and Linux
USD plugin version: https://github.com/Autodesk/maya-usd/releases/tag/v0.1.0

**Comment by martin-pw** [comment] 2020-03-30 21:45
Sample file attached.

[smarties.zip](https://github.com/Autodesk/maya-usd/files/4405663/smarties.zip)

**Comment by santosg87** [comment] 2020-04-02 16:04
Hi Martin, thank you for logging this.

I am also able to reproduce this behavior on our side. we will investigate this further.

changing the assignment for now as we decide on the next steps.

**Comment by fowlertADSK** [comment] 2020-04-02 16:41
FYI for @santosg87 
I already have a fix that is in: https://github.com/Autodesk/maya-usd/pull/396
But I have not tested Martins Maya batch workflow, only the dragging onto Maya problem.

**Comment by santosg87** [comment] 2020-04-02 16:55
that's awesome to hear! I will keep an eye for it when the changes are in :)

**Comment by kxl-adsk** [comment] 2020-11-06 18:25
Closing since it was fixed internally. @martin-pw please reopen if we missed something.

**Closed by kxl-adsk** 2020-11-06 18:25 UTC
Labels: bug, import-export, reproduced
