### ISSUE TITLE
[MAYA-113230] ALab loading speed bottleneck

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#1624] opened 2021-08-13 17:40 UTC
**Describe the bug**
Hi there,

I believe there is some kind of bottleneck while loading ALab scene with MayaUSD plugin. Tested on both 0.10.0 and 0.11.0
I feel like Proxy and Render purpose is loading in the same time so the time to first "pixel" is stretched to 38 seconds. This is way too long for such simple scene.

**Steps to reproduce**
1. Load the ALab scene.

**Expected behavior**
In my humble opinion Render purpose should load only on "demand" or during actual Render time. 
Proxy version is low poly and has no textures assigned so it should load in less than a second. 
For instance model with 2000 separate objects and 50M polys loads in 4 seconds.

Video with comparison https://www.youtube.com/watch?v=lHjzs4_hENE

**Specs (if applicable):**
 - Windows 10 20H2
 - MayaUSD plugin 0.11.0
 - Maya PR127

**Comment by Xaia** [comment] 2021-08-15 12:25
Just for the comparison, here is how Houdini is loading this stage. Geo loads in an instant and then textures are quickly loaded in. 
Also the Alab is rendering with Karma without any issues. Arnold is not rendering the Alab at all. 
https://user-images.githubusercontent.com/60515654/129478474-0d7c4d7e-e6ad-4b7d-bd74-854c34984bfe.mp4

**Comment by wtelford** [comment] 2021-08-16 13:39
@santosg87 can you link this to internal issue MAYA-113230 ?

**Comment by williamkrick** [comment] 2021-08-16 18:53
@Xaia the long loading time is caused by texture loading. USD only synchronizes rprims whose purpose is necessary to draw the scene, but it synchronizes _all_ the sprims. When the scene loads in with only proxy purpose displayed the time taken is all the time to load the proxy geometry & materials plus all the time to load the render materials. And the render materials take up most of the time!

I reproduce a similar long load time in UsdView. There if I disable every render purpose and load the scene, it still takes me about 40s to load. I logged an issue against USD, https://github.com/PixarAnimationStudios/USD/issues/1597, to track this.

I suspect that Houdini is fast because their texture loading is asynchronous. During the actual USD load step their sprim sync calls are all fast, and so the scene appears right away without textures. Then, as textures load in the background they appear in the viewport.

**Comment by Xaia** [comment] 2021-08-16 19:42
@williamkrick thank you for checking what is exactly causing this issue. Would be a bummer to lose all the magnificent USD speed just because of some puny textures ;).

**Comment by williamkrick** [comment] 2021-08-17 13:01
Yes hopefully we'll be able to find a solution to this problem.

I did create a pull request for an issue I found during my investigation which saves syncing rprims which are not drawn. In ALab this doesn't provide a measurable performance improvement because the time all goes to sprims (the materials).

There is no similar way to have sprims respect purpose for sync that is easy for me to implement, but we'll keep on looking for a solution.

**Comment by swillisart** [comment] 2021-08-24 19:37
@seando-adsk  This should not be closed as William stated in his PR it does not resolve this specific issue.

**Comment by seando-adsk** [comment] 2021-08-24 21:05
I didn't intentionally close this issue. I think because I merged #1633 it was an automatic Github thing. I've reopened this.

**Comment by noWookies** [comment] 2021-11-23 22:46
Hi @wtelford , we're hoping to start using textures (much) more frequently in our pipeline soon and this is starting to shape up as a blocker. Would there be a way to give it a priority bump ?

**Comment by wtelford** [comment] 2021-11-23 22:48
This is something we are investigating.

**Comment by kxl-adsk** [comment] 2021-11-23 23:16
@noWookies One thing worth mentioning here is that we identified an issue in Hydra and logged it as https://github.com/PixarAnimationStudios/USD/issues/1597.

**Comment by csyshing** [comment] 2022-02-15 04:00
Putting a note here: https://github.com/Autodesk/maya-usd/pull/1980 should help to improve the loading performance.

**Comment by williamkrick** [comment] 2022-02-15 14:22
I've passed this one to our internal QA to test the async texture loading performance and stability. Once we feel it is ready I'll switch the behavior so that the async loading is on by default.

For now you'll have to set the optionVar value to get the performance improvement:

`cmds.optionVar(iv=("mayaUsd_DisableAsyncTextureLoading", 0))`

**Comment by santosg87** [comment] 2022-07-13 18:02
Closing this issue for now, as we have it fixed internally. if this is still an issue, feel free to reopen. :)

**Closed by santosg87** 2022-07-13 18:02 UTC
Labels: bug
