### ISSUE TITLE
FrameSelected does not correctly frame on selected point instances.

### ISSUE THREAD

**Issue by jufrantz** [Autodesk/maya-usd#3410] opened 2023-10-23 17:31 UTC
**Describe the bug**

Using `F` hotkey in a modelEditor to frame on a point instance selection, the view is not tightly fitted to the point instance bounds. The camera center of interest is adjusted to the instance position, but the view seems to be filled with the whole instancer bounding box.

**Steps to reproduce**

1. Create a mayaUsd proxyShape with an usd point instancer. 
```python
import maya.cmds
import mayaUsd.ufe
import mayaUsd_createStageWithNewLayer

maya.cmds.loadPlugin("mayaUsdPlugin", quiet=True)

proxyShape = mayaUsd_createStageWithNewLayer.createStageWithNewLayer()
shapeStage = mayaUsd.ufe.getStage(proxyShape)

shapeStage.GetRootLayer().ImportFromString('''#sdf 1
(
    defaultPrim="PI"
)
def PointInstancer "PI"
{
    point3f[] positions = [(0, 0, 0), (100, 0, 100), (100, 0, -100), (-100, 0, -100), (-100, 0, 100)]
    int[] protoIndices = [0, 0, 1, 1, 1]
    rel prototypes = [</PI/Protos/Sphere>, </PI/Protos/Cube>]

    def Scope "Protos"
    {
        def Sphere "Sphere" {}
        def Cube "Cube" {}
    }
}
''')
```

2. Select a point instance and try to frame it by using viewFit command or  `F`` key.
```python
maya.cmds.select(f"{proxyShape},{shapeStage.GetDefaultPrim().GetPath()}/4")
maya.cmds.viewFit("persp")
```

3. Notice that the view is not correcty fitted to the selected point. 

**Specs (if applicable):**

 - CentOS 7.8
 - Maya 2023.3
 - maya-usd 0.25
 - USD 22.11

**Comment by swillisart** [comment] 2023-10-24 21:18
I believe this is a duplicate of : https://github.com/Autodesk/maya-usd/issues/3377

**Comment by jufrantz** [comment] 2023-10-25 09:06
Thank you @swillisart for pointing it out, definitely duplicate of #3377. 
I'm closing this one.

**Closed** 2023-10-25 09:07 UTC
Labels: bug
