### ISSUE TITLE
Load/unload payloads broken with anonymous root layers

### ISSUE THREAD

**Issue by Jimmy-LeeBoisvert** [Autodesk/maya-usd#2541] opened 2022-08-10 17:43 UTC
**Describe the bug**
Since Maya USD 0.17.0 (currently at 0.18.0 at the time of writing this), any opinion stored in an anonymous layer (e.g. a defined prim or adding sublayers) from a MayaUsdProxyShape node is permanently gone when the "Load payloads" checkbox is unchecked and then checked again.

In 0.15.0, when there were buttons to load and unload payloads, all opinions remained when the payloads when unloaded and then reloaded.

This seems like a bug, as unloading a payload should normally not affect prims that are defined directly in the anonymous layer, but should rather only unload actual payloads.

**Steps to reproduce**
1. Open Maya 2022 or Maya 2023 with Maya USD 0.18.0.
2. Click on the "Create" menu, go to "Universal Scene Description (USD)", and then "Stage with New Layer".
3. In the Outliner, make sure shapes are displayed, and select the newly created MayaUsdProxy shape node called "stageShape1".
4. Right-click on the "stageShape1" node, go to "Add New Prim" and select "Def".
5. Notice the "Def1" prim that just got created.
6. Select again the "stageShape1" in the Outliner.
7. Go to the Attribute Editor, and expand the "Extra Attributes" section.
8. Uncheck "Load Payloads".
9. Notice that the "Def1" prim is gone, despite not being an actual payload.
10. Check "Load Payloads".
11. Notice that the "Def1" prim is **not** back.

**Expected behavior**
The expected behavior is that only actual payloads (USD layers referenced from specific prims using the "payload" attribute) should be affected by the "Load Payloads" state, even when the root layer is anonymous.

In Maya USD 0.15.0, with the "Load All" and "Unload All" payload buttons, the "Def1" prim never disappears, and actual payloads disappear and re-appear as expected.

**Specs (if applicable):**
 - Maya 2022 and Maya 2023
 - Maya USD 0.17.0 and 0.18.0

**Comment by santosg87** [comment] 2022-08-16 19:58
Thank you for logging this @Jimmy-LeeBoisvert. I was able to reproduce this issue on our side as well.

The good news is that i can't reproduce this on our internal builds. so this is something that should be fixed on the next incoming builds when those are available! :) once the binaries are available we can confirm it on your side and hopefully have this solved for you!

cheers,

**Comment by santosg87** [comment] 2022-09-19 13:59
@santosg87 this should be fixed on our latest release of MayaUSD. are you able to confirm and close? thank you!

**Comment by Jimmy-LeeBoisvert** [comment] 2022-09-19 17:49
Hello @santosg87 from some quick tests, it seems to be working. Thank you!

I found another issue related to the payload checkbox where edit layer is being switched to the session layer when checking and unchecking it, should I create another issue for that?

**Comment by santosg87** [comment] 2022-10-12 03:26
@Jimmy-LeeBoisvert yes, please log that one separately, that way we can keep track of things a bit better.

for the time being, I am marking this issue as closed. :)

cheers

**Closed by santosg87** 2022-10-12 03:26 UTC
Labels: bug
