### ISSUE TITLE
refactoring_sandbox : Unloading mtoh.mll crashes Maya even when no Hydra viewport active

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/maya-usd#81] opened 2019-10-25 19:06 UTC
### Issue

Maya crashes when unloading the `mtoh` plug-in and at least one Hydra viewport has been active.

#### To reproduce

1. Load `mtoh` plug-in.
2. Set viewport to `Hydra (GL)`
3. Unload `mtoh` plug-in. Crash.

It doesn't matter whether you do new scene or set viewport back to Viewport 2.0 before step 3.

### Specs

- Windows 10
- Maya 2019.2
- refactoring_sandbox ( [`d0bb624`](https://github.com/Autodesk/maya-usd/commit/caa921c1cb3b59ea6acc84540ebea9a05b1fedf9) ) 
- Pixar USD dev ( `b85ddac2` )

**Comment by fowlertADSK** [comment] 2019-10-31 20:04
Thanks for logging this Roy.  I was taking a quick look but was hitting some of the other issues that you've got logged.  I see Huidong has submitted at least one fix in the same area of code that I don't have in my current build so I'll probably wait until I have the latest before coming back and trying to reproduce this one again.

**Comment by HdC-adsk** [comment] 2019-11-05 15:51
This is a different issue. There is a plugin callback function pointer from mtoh which is invoked after the plugin is unloaded.  Looks like something is not deregistered properly during plugin unloaded.

**Comment by santosg87** [comment] 2020-03-11 18:22
note that this should be fixed on the latest Maya PR builds. :)

**Comment by santosg87** [comment] 2020-03-30 18:16
Marking this one as closed, for now, as it seems fixed, based on our testing, using the most recent dev-branch plugin.

**Closed by santosg87** 2020-03-30 18:16 UTC
Labels: bug, mtoh, question

**Comment by ChangCalvin** [comment] 2022-08-08 19:09
Maya 2023 crashes
