### ISSUE TITLE
MAYA-114407 Crash when using "Show Selection" on a child of a hidden proxy shape

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1761] opened 2021-10-18 15:12 UTC
**Describe the bug**
If the proxy shape is hidden & the user selects a node under it & tries to use "Display" -> "Show Selection" or Shift+H, it will crash Maya.

**Steps to reproduce**
1. Open a new file in Maya 2022
2. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
3. Right click on the proxy shape -> Add new prim -> Capsule
4. Click on the proxy shape in the outliner and press Ctrl+H to hide it
5. Click on the capsule in the outliner and press Shift+H (or Display->Show Selection) to show selection
Step 5 triggers the crash.

Top of the stack trace:
> Stack trace:
>   /dist/sw/maya/2022.update2/lib2/libSharedUI.so(+0x4c97ea) [0x7f24873f27ea]
>   TmetaCommand::doCommand(TargList&)
>   /dist/sw/maya/2022.update2/lib2/libCommandEngine.so(+0x9cf44) [0x7f2480d34f44]
>   /dist/sw/maya/2022.update2/lib2/libCommandEngine.so(+0xc7109) [0x7f2480d5f109]
>   /dist/sw/maya/2022.update2/lib2/libCommandEngine.so(+0xc72a1) [0x7f2480d5f2a1]
>   SophiaExecutable::evaluate(void*)
>   TcommandEngine::executeCommand(SophiaExecutable*)

**Expected behavior**
In Maya 2020, if you attempt to "Show Selection" of a node and its parent is invisible, it will reveal the parent. 

**Specs:**
OS (Linux 64 bit)
Maya USD: dev at 4710d36
Pixar USD: dev at 96c5a3f
Maya 2022.update2

Thank you!

**Comment by santosg87** [comment] 2021-10-22 03:41
thank you for logging this.

I am also able to reproduce this issue on our side. it seems we have 2 bugs here, when comparing to Maya data behavior.
1. crashing - looks like 2020.4 builds don't crash :)
2. When trying to display a child of a hidden parent, when on USD data, nothing happens, ideally the same behavior of Maya data should be happening here.

**Comment by santosg87** [comment] 2022-01-17 18:48
@gracekumagai this issue should be fixed on the latest version of plugin, are you able to confirm?

**Comment by gracekumagai** [comment] 2022-01-18 17:34
Hey @santosg87, from the two issues in this ticket:
1. I'm still running into the crash with the same repro steps
2. This issue seems resolved! When trying to display the child of a hidden parent, it seems to have the same behaviour as native Maya :)

I'm testing with:
maya2022.update3
maya-usd dev at 807a118

**Comment by santosg87** [comment] 2022-03-11 15:15
for the crash, i believe the changes are required on the Maya side, so this would have to be included on a maya update. :)

**Comment by santosg87** [comment] 2022-03-31 15:04
hi @gracekumagai,

with the release of Maya 2023 - this issue should now be fixed on that version. would you be able to confirm it on your side?
cheers!

**Comment by santosg87** [comment] 2022-04-22 15:16
closing this issue for now. @gracekumagai feel free to reopen if this is something that is still an issue and we would need to investigate backporting.

**Closed by santosg87** 2022-04-22 15:16 UTC
Labels: bug, requires maya
