### ISSUE TITLE
Failed verification: ' shader ' -- Coding Error in GetFallbackShader at line 266

### ISSUE THREAD

**Issue by agelosc** [Autodesk/maya-usd#361] opened 2020-03-17 10:24 UTC
When I create UsdReferenceAssebly and load an usd file (ie. Hello World from the pixar tutorials ) I get this error in maya:
`Failed verification: ' shader ' -- Coding Error in GetFallbackShader at line 266 of <localpath>\maya-usd\lib\render\vp2RenderDelegate\render_delegate.cpp`

This error is issued in all Scene Assembly modes except Full. 

 - Windows 10
 - Maya 2020
 - Built few days ago with the latest versions of both maya-usd and pixar-usd.

**Comment by santosd** [comment] 2020-03-18 19:23
Hello @agelosc, I tried this out in the latest Maya (PR113) and maya-usd I was not able to replicate the issue. I used the Hello World example from Pixar and when I bring that usd file in I don't get any errors. I also tested in Maya 2020 using the latest [builds](https://github.com/Autodesk/maya-usd/releases). Would you be able to give this a try on the latest build and and see if you are still getting the errors?

**Comment by agelosc** [comment] 2020-03-19 07:51
Thank you for having a look. I compiled and tried the binaries of yesterday's release but the Pixar Maya plugin was not included so I can't check the pxrUsdReferenceAssembly since it belongs to it. I'm still trying to understand which branch and release is best to pull so please let me know if I've missed something.

**Comment by santosd** [comment] 2020-03-31 13:19
Hi @agelosc, Initially I thought you were doing this on the Maya USD plugin and not the Pixar one. To clear up some of the confusion: The current plan is to take the Pixar plugin and the Animal Logic plugin and work together to make one plugin (Maya USD). The goal is to eventually cover the Pixar and Animal Logic workflows using the Maya USD plugin. However, if there are issues in the Pixar plugin or Animal Logic ones, especially any regressions we definitely want to be aware of them. Since I tested this on the Maya USD plugin and not the Pixar one, I will take a look on that end and let you know if I am able to reproduce the issue.

**Comment by santosd** [comment] 2020-04-07 15:23
Hi @agelosc , I tested this out on my end using the pixar plugin and Maya PR114 and I am not seeing that error message when I create a reference assembly and then load a prim such as the sphere from the hello world tutorial. All seems to be working well on my end using a recent build. Unfortunately I'm not sure what the issue could be on your end, possibly an issue in the build process?

**Comment by agelosc** [comment] 2020-04-07 17:29
My apologies for the confusion. I realise now that I didn't write which reference proxy correctly in my first post. 

Since this is not reproducing should I mask this as internal? Either way thank you for having a look at this.

**Comment by HdC-adsk** [comment] 2020-04-14 22:53
@agelosc What do you mean by "internal" in this case? Internal to whom?

The error in your first post comes from VP2RenderDelegate instead of Pixar USD. If you cannot reproduce it, I would suggest to close the issue.

@santosd , I also have a PR #431 which fixes a similar issue (shader error when running command-line render). Could you retest this case reported by @agelosc ? Thanks.

**Comment by agelosc** [comment] 2020-04-15 06:21
I was under the impression internal meant that the issue was due to local configuration and not a bug. I can reproduce the error but the comments above point to that direction. Sorry for the misunderstanding. Please go ahead and close this issue if that's the case.

**Comment by HdC-adsk** [comment] 2020-04-15 11:24
NP.  You can still reproduce the issue, so I think it is probably better to keep this bug open and I will ask you to retest once #431 is merged (not sure that PR helps in this case but it fixes a similar issue for command-line render). Thanks.

**Comment by HdC-adsk** [comment] 2020-05-26 15:09
@agelosc Is the issue still reproducible on latest code? There is a chance that #431 has fixed it.

**Comment by agelosc** [comment] 2020-05-26 16:34
No, you're right. This error is not showing up anymore in the build I have at the moment. Not sure if I'm supposed to close this issue or you so please go ahead and close it or let me know if I should. Thanks for having a look at this.

**Comment by santosd** [comment] 2020-05-26 17:01
@agelosc thanks for confirming that this issue is no longer happening. I have gone ahead and closed this issue.

**Closed by santosd** 2020-05-26 17:01 UTC
Labels: bug, pxr, question, vp2renderdelegate
