### ISSUE TITLE
Maya UFE : Renamed Prims Lost After File Save and Re-open

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#308] opened 2020-02-26 16:22 UTC
**Describe the bug**
After https://github.com/Autodesk/maya-usd/issues/75 was resolved, the renamed prim is now lost after file save and re-open.

This is most likely due to the session layer edit made after the rename was completed :

```
#usda 1.0
over "pSphere3" (
    active = false
)
{
}
```

**Steps to reproduce**
1. open included 3_Spheres example or scene of your choice.
2. select prim
3. rename prim
4. observe session layer
5. save file
6. re-open file
7. notice renamed prim is now missing ( original prim is de-activated )

**Expected behavior**
Renamed prim does not disappear.  Session layer should probably look different than it is now.

**Attachments**

[3_Spheres_Example.tar.gz](https://github.com/Autodesk/maya-usd/files/4256873/3_Spheres_Example.tar.gz)

( Renaming Prim )
![pr112_rename](https://user-images.githubusercontent.com/2152250/75363718-821da980-5888-11ea-9054-02f42dd65821.png)

( Result after save and re-open )
![renamedPrimLost](https://user-images.githubusercontent.com/2152250/75363729-84800380-5888-11ea-9ecf-3c7b4daea2b6.png)

**Specs (if applicable):**
 - OS & version [e.g. Windows 10] 
 - Compiler & version [e.g. gcc 6.3.1]
 - Maya version [e.g. Maya 2020] Beta
 - Maya USD commit SHA [e.g. dev at 44e597f]
--

]
 - Pixar USD commit SHA [e.g. dev at b85ddac2]

**Additional context**

**Comment by santosd** [comment] 2020-03-12 12:53
Hello @cfmoore007, I tested this out on the latest beta release PR113 and was not able to reproduce, so it seems to me that the issue has been resolved. Could you download the latest beta version and see if you are still seeing the issue?

Thank you.

**Comment by cfmoore007** [comment] 2020-03-12 15:35
I just tried with the latest maya-usd dev and PR113.

1) AL Proxy Shape ( Still Broken )
The renamed prim is missing from the viewport and the UFE prims in the outliner.  Same results as I posted above.

2) Maya Proxy Shape ( Fixed )
![PR113_renameAfterSave](https://user-images.githubusercontent.com/2152250/76538241-62c07800-6455-11ea-9cb8-02c5ae28d002.png)

**Comment by santosd** [comment] 2020-03-13 20:13
@cfmoore007 thanks for the information. I had tested this on the Maya proxy not the AL one. I will mark label this issue as AL so it can be looked at on that end. Thanks again.

**Comment by santosd** [comment] 2020-04-09 12:57
I took another look at this using the AL plugin and was able to reproduce it on that end.

**Comment by santosg87** [comment] 2024-09-16 14:20
closing this issue for now. as it is currently working on MayaUSD.

**Closed by santosg87** 2024-09-16 14:20 UTC
Labels: bug, al, ufe-usd, workflows, reproduced, regression
