### ISSUE TITLE
Importer does not clear USD Layer Cache

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#974] opened 2020-12-04 20:58 UTC
**Describe the bug**
The USD importer does not clear the layer cache between consecutive imports.
This means that if the usd file on disk is modified between two imports, the second import will be incorrect.

**Steps to reproduce**
1. Import attached usda file
2. Create a new scene in Maya
3. Edit the usda file so pCube1 has a different name
4. Import usda file again
5. see that it comes in under its old name

**Expected behavior**
I would expect the second import to respect the contents of the file on disk, rather than the sdf layer cache.
Perhaps it would be best if each import specifically cleared the cache, or had an option that was on by default to do so?

**Attachments**
[anim_mesh.usda.zip](https://github.com/Autodesk/maya-usd/files/5645387/anim_mesh.usda.zip)

**Specs (if applicable):**
 - macOS Catalina and Big Sur
 - Compiler version: Apple clang version 12.0.0 (clang-1200.0.32.5) (reproducible on older clang versions too)
 - Maya 2020.0
 - Maya USD commit SHA ddcd319b7785a8cc586b3106ecd16cba25f9cb3c
 - Pixar USD commit SHA d8a405a1344480f859f025c4f97085143efacb53

**Comment by santosd** [comment] 2021-05-24 20:46
Hello @dgovil,

I Gave this a try in Maya PR125 using the PR125 build of Maya USD and I am not able to reproduce the issue that you are seeing on your end. Would it be possible for you to test in PR125 or a newer version to see if the issue is resolved?

**Comment by santosd** [comment] 2021-07-26 20:39
Hi @dgovil, Just checking back on this to see if you had a chance to test this in a recent PR release to see if the issue is still reproducible for you.
Thank you.

**Comment by dgovil** [comment] 2021-07-26 20:40
Not yet unfortunately. I'm mid move this week but will try out the latest PR next week and see if I can still reproduce this.

**Comment by santosd** [comment] 2021-08-09 20:12
Hi @dgovil, Just wanted to check back on this one and see if you had a chance to take a look at this issue again in a newer build. If you are not able to test at this time, let us know and we can close this issue for the meantime and reopen if we need to once you have had a chance to test. Thank you.

**Comment by dgovil** [comment] 2021-08-09 20:21
Hi David,
Sorry again,Please go ahead and close it and I'll open a new issue if
needed. I just finished moving and haven't had adequate internet service to
get the latest builds up and running.

**Comment by santosd** [comment] 2021-08-10 17:29
No problem at all @dgovil, Hope the move went well. If at a later time you still have issues with this, feel free to comment on it again and we can reopen it.

Cheers!

**Closed by santosd** 2021-08-10 17:29 UTC
Labels: bug, import-export
