### ISSUE TITLE
Blendshape Target Names have a zero at the end of the names

### ISSUE THREAD

**Issue by stevkalinowski** [Autodesk/maya-usd#1235] opened 2021-03-04 23:03 UTC
**Describe the bug**
If a blendshape mesh has had its target mesh objects deleted, then when a usd file is exported the target names get an extra 0 appended to the end of the names.

Note, the bug does not happen if the blendshape targets still exist in the scene when exported.

**Steps to reproduce**
1. Open the attached file "blendshape_test_bug.ma"
2. File > Export All
3. Use settings "Subdivision None" "Skeletons All" "Skin Clusters All" "Blendshapes on" and "File Format ASCII"
4. Export the file
5. Open the file in a text editor and search for "jawOpen" and notice the name is "jawOpen0"

**Expected behavior**
The blendshape names should match exactly the name of the blendshape attributes in the Maya scene.

**Attachments**
Added 2 files, one example of working correctly and one file exhibiting the bug.

**Specs (if applicable):**
 - OS Windows 10
 - Maya PR122

[blendshape_test.zip](https://github.com/Autodesk/maya-usd/files/6087115/blendshape_test.zip)

**Comment by dgovil** [comment] 2021-03-04 23:31
AFAIK this should be fixed in the [0.8 release](https://github.com/Autodesk/maya-usd/releases/tag/v0.8.0) of the plugin thanks to @ysiewappl in https://github.com/Autodesk/maya-usd/pull/1149.

**Comment by ysiewappl** [comment] 2021-03-06 08:40
Would like to clarify here: the suffixes are appended because a single blendshape "weight" in Maya is capable of driving multiple targets at the same time (i.e. inbetweens). Therefore we require a way to namespace these targets in order to avoid collisions, but only if your original target meshes have been "baked" (i.e. we no longer have a way to traverse back to the original mesh nodes to grab the names from). Dhruv's actual described case might still cause a collision, now that I think about it...

**Comment by stevkalinowski** [comment] 2021-03-08 18:08
Is there any way of using a special character that isn't reserved yet instead of appending to the name?  We could detect and correct if it was done that way.  Otherwise, we have no way of knowing if the exporter mangled the name, or if a user intentionally appending a number.

If a special char is possible, we should investigate as many DCCs as possible to ensure we don't use a char that another DCC perhaps supports.  Just a thought.

**Comment by ysiewappl** [comment] 2021-03-08 20:55
> Is there any way of using a special character that isn't reserved yet instead of appending to the name? We could detect and correct if it was done that way. Otherwise, we have no way of knowing if the exporter mangled the name, or if a user intentionally appending a number.
> 
> If a special char is possible, we should investigate as many DCCs as possible to ensure we don't use a char that another
> DCC perhaps supports. Just a thought.

Sorry, to clarify: the suffixes are appended _only_ if you baked the targets down, which means that there is no other
possible way to retrieve a meaningful name for the targets even within Maya. Even if we namespaced the names, you should
not be relying on those "mangled" names to determine behaviour; the prim names of the blendshapes themselves (which
should match that of what you see within Maya on the weight plug aliases) are what you should be using instead, if you
were relying on specific target names for a reason; those will remain unchanged. 

Using special characters is not a good idea since they still need to be valid `SdfPath`s at the end of the day.

**Comment by stevkalinowski** [comment] 2021-03-08 21:28
when you say "the prim names of the blendshapes themselves", do you mean the target shape's mesh node?  In our case the targets will have been deleted.  So when that's the case, is the data still inside the usd file to retrieve?

**Comment by ysiewappl** [comment] 2021-03-12 17:53
> when you say "the prim names of the blendshapes themselves", do you mean the target shape's mesh node? In our case the targets will have been deleted. So when that's the case, is the data still inside the usd file to retrieve?

Hi: yes, that's what I refer to as "baking" the targets. Your target data will always be inside the USD file to retrieve; what I'm saying is that instead of referring to the names in the `UsdSkelRoot`:

```
        uniform token[] skel:blendShapes = ["_blendShape24_tgt1", "_blendShape24_tgt0"]
        rel skel:blendShapeTargets = [
            </basic_skinned_cube_duplicate_targets_names_across_meshes/base0/tgt1>,
            </basic_skinned_cube_duplicate_targets_names_across_meshes/base0/tgt0>,
        ]
```

which may or may not include namespacing information, it would probably be a better idea to refer to the names at the Blendshape prim level, i.e.

```
        def BlendShape "tgt1"
        {
            uniform vector3f[] normalOffsets = [(0, 0, 0)]
            uniform vector3f[] offsets = [(0.1364052, 1.15968, -1.985774)]
            uniform int[] pointIndices = [4]
        }
```
Since these should match what your weight plug aliases are in Maya. In-between targets are an exception (since that is an example of a "single weight plug driving multiple targets" situation that we try to find the original mesh targets for); if you have them baked, we suffix the target names there too to ensure that we do not have collisions.

**Comment by wtelford** [comment] 2021-06-28 20:13
@santosd can you repro this for us?

**Comment by santosd** [comment] 2021-07-02 17:42
@stevkalinowski I tested this in Maya using PR126 from the beta site and was not able to reproduce the issue using the files you provided. I also tested the latest 2022.1 release and was not able to reproduce the issue there. When I search for "jawOpen" in the exported USD file from the "blendshape_test_bug.ma" file I get "jawOpen" nothing with a "0" in it. Could you get the latest and test again on your end to confirm if the issue has been resolved. Maybe I am missing something on my end, but I followed the steps provided and was not getting the issue.

**Comment by stevkalinowski** [comment] 2021-07-06 20:56
Thanks for looking into it.  I just tested in Maya 2022 and I do not see the issue anymore with the test files I provided.  It looks to be resolved.

**Comment by santosg87** [comment] 2021-07-12 21:22
closing this one based on the above comments :)

**Closed by santosg87** 2021-07-12 21:22 UTC
Labels: bug, import-export
