### ISSUE TITLE
[MAYA-111092] Reference USD not using namespaces

### ISSUE THREAD

**Issue by ghostvfx-jimmy** [Autodesk/maya-usd#1307] opened 2021-04-06 13:05 UTC
**Describe the bug**
When creating a USD reference, namespaces are not applied.

**Steps to reproduce**
1. Create reference..
2. Enable "Use namespaces"
3. Select a USD file and chose "Reference"
4. Reference created without namespace.

**Expected behavior**
When creating a reference with "Use namespaces" enabled, it's expected that it's with namespace.

**Specs (if applicable):**
 - Linux
 - Maya 2020.4
 - Maya USD v0.8.0 (release from this site)

**Comment by santosd** [comment] 2021-04-06 16:37
Hello @ghostvfx-jimmy, I gave this a try on my end and I was not able to reproduce the issue you are seeing. When I follow those same steps and use the namespace option to use the file name, I see a namespace created with the file name. If I use the option for a string, it uses the string I specify. In both instances I can open the Namespace Editor and verify that a new namespace is created.

**Comment by ghostvfx-jimmy** [comment] 2021-04-08 09:35
Yes, the namespace is created but the objects within the reference is not using the namespace.

Eg.:
If you import `sphere.usd` with `pSphere1` object twice, the second import will rename the object to `pSphere2`. Normally it would be called `sphere:pSphere1` and `sphere1:pSphere1`.

Also even if the namespace is created, using the namespace editor > Select  Content doesn't work for the USD reference.

**Comment by santosd** [comment] 2021-04-08 15:49
@ghostvfx-jimmy Thank you for clarifying that for me. I definitely see the issue now. I will mark this issue as reproduced and will review it with the team to see about getting a fix going for it.

**Comment by Xaia** [comment] 2021-12-09 16:45
hi @santosd any update on this issue? It's a quite big show stopper. Would love to see that fixed :)

**Comment by santosd** [comment] 2021-12-09 19:07
Hello @Xaia, This issue is still in our backlog and has not been fixed internally. I will bring it up to the team to let them know that this is a showstopper for you so that we can set it at a higher priority.

**Comment by santosd** [comment] 2022-02-07 17:41
Hi @Xaia there was a change that went in recently that seems to have fixed this issue on my end. Would you be able to build the latest and test again? Otherwise we can wait until the next release and you can test at that point to see if it is working for you
![namespaceReference](https://user-images.githubusercontent.com/29235905/152842112-07478076-4fbe-43f1-aa14-2fa5a28355d8.gif)
.

**Comment by ghostvfx-jimmy** [comment] 2022-02-14 11:11
I hate to break it to you, but the clip actually shows the bug. The issue is not wether or not it's getting a reference group, but the fact that the referenced geometry is not assigned a namespace prefix. This means that a second import will change the name of the object (adding a suffix).

So instead of just being named `pPlane13` it should have been called `colorTest:pPlane13`

**Comment by santosd** [comment] 2022-02-14 19:51
Hi @ghostvfx-jimmy, I do see that. It looks like there was a little more support added for namespaces but we are not fully there yet. The ticket we have logged internally remains open and we will be taking a look at the issue.

**Comment by jacobvfx** [comment] 2022-04-07 08:48
Any progress on this issue?

It's a big roadblock moving forward with USD in Maya. 
It breaks the normal convention of what a Maya Reference is and doesn't match the behavior you get when loading in a ma/mb or alembic file.

**Comment by santosd** [comment] 2022-04-08 15:54
Hi @jacobvfx,
No updates on this as of yet. We have the issue scheduled to be worked on for an upcoming release so hopefully we are able to work on this soon. I will be sure to let the team know that this is an adoption blocker for a lot of users.

**Comment by ppt-adsk** [comment] 2022-04-26 17:47
Hello @jacobvfx, @Xaia, @ghostvfx-jimmy.  Bug is fixed here:
https://github.com/Autodesk/maya-usd/pull/2308
Trivial fix in the end, but which ended up revealing another problem: this behavior (import not supporting namespaces) has been here since the beginning of the Pixar Maya USD plugin, was copied over to the Autodesk plugin, and its effect has been incorporated into maya-usd automated tests (which I have fixed).

We are concerned that some users of maya-usd import are actually relying on the bug, and assuming imported nodes won't be in a namespace.  Of course, these users should actually fix their code and not ask for namespace support, but we want to make sure we aren't disruptive in fixing this bug, and don't require mitigating measures e.g. like an environment variable to preserve the legacy (buggy) behavior.

My personal preference is to do this cleanly, fix the bug, adjust the broken tests, which is what I have done, and I hope that maya-usd users will do the same.  Is this a reasonable way to proceed?  Your opinions quite welcome.

**Comment by daviddeacon** [comment] 2022-04-26 20:44
I agree in fixing cleanly and not worry about users that rely on the code bug. Just make sure the change is mentioned in the release notes. 

It’s an in alpha for a reason.

**Comment by cescocm** [comment] 2022-04-27 04:59
Hi, @ppt-adsk I also agree that being these versions are still in development any integration can assume these types of bug fixes. And users that are actually relying on the bug, and assuming imported nodes won't be in a namespace can easily have their wanted behaviour back as long as they are informed of the change so they can react. 

I think that it would be completely inconsistent to do this in a different way (environment variables, making the default being not namespace, or whatever this might be that is not matching the normal behaviour for all the other formats).

My 2 cents.

**Comment by ppt-adsk** [comment] 2022-05-12 19:05
Merged to dev branch here:
https://github.com/Autodesk/maya-usd/commit/89ae0a70fb3a6b398d4dcf5558e78e4f556d5f72
Thanks for your feedback!

**Comment by santosg87** [comment] 2022-09-19 14:19
based on the comments above and the commits, i believe this can now be closed.

feel free to reopen/log a new issue if there are problems with this still.

**Closed by santosg87** 2022-09-19 14:19 UTC
Labels: bug, reproduced
