### ISSUE TITLE
Multi-parenting not working

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#814] opened 2020-10-02 11:41 UTC
**Describe the bug**
After creating a Def, when trying to drag-drop multiple existing prims underneath it, Maya only successfully parents the first.  

This does not seem to be a USD Outliner 'syncing' issue because if you print out the layer, you will only see pSphere1 ( not 2 or 3 ) underneath the `def Def`.

**Steps to reproduce**
1. Create stage from File with the example.
2. Edit target is the same as the file ( not the session layer as in my other issue )
3. Right-click on the stage to create a Def Prim
4. Select and middle-mouse drag the spheres underneath the Def Prim
5. Witness incorrect results.

**Expected behavior**
All selected spheres are successfully parented under the new Def Prim

**Attachments**
![multiparentNotWorking](https://user-images.githubusercontent.com/2152250/94919424-73345080-0482-11eb-82fb-e32844b4ba28.png)
[3_Spheres.zip](https://github.com/Autodesk/maya-usd/files/5317663/3_Spheres.zip)

**Specs (if applicable):**
 - OS & version [ Windows 10 ]
 - Compiler & version [ Visual Studio 2017 ]
 - Maya version [ Maya Beta PR 119 ]
 - Maya USD commit SHA [ dev at f94bcfa ]
 - Pixar USD commit SHA [ 20.08 ]

**Additional context**

**Comment by HamedSabri-adsk** [comment] 2020-10-17 01:44
@cfmoore007  This issue should be fixed with the latest improvement on parenting work flow.
  
f94bcfa is quite old.  Sync to dev's HEAD and try things again. 

FWIW, here is the screenshot from my local build with parenting working as expected:

![parenting](https://user-images.githubusercontent.com/48299423/96325687-d16f4080-0ff7-11eb-9629-ec7c5d24b9b4.gif)

**Comment by cfmoore007** [comment] 2020-10-19 11:20
Great!  Thanks for the update.

**Comment by santosg87** [comment] 2021-07-12 20:58
I believe this can be closed. the issue @cfmoore007 mentions on the def prim is due to limitations on the prim type, we have an error message that mentions the limitation now. :)

marking this as closed for now, we can re-open if the issue is still a problem

**Closed by santosg87** 2021-07-12 20:58 UTC
Labels: bug, workflows
