### ISSUE TITLE
Skinning Lost when exporting or importing.

### ISSUE THREAD

**Issue by stevkalinowski** [Autodesk/maya-usd#610] opened 2020-06-29 20:28 UTC
**Describe the bug**
If I export a usd file with joints and skinning, when I import the usd back into Maya the meshes do not have skin clusters.

**Steps to reproduce**
1 open the sample scene in the attached zip
2 run this export mel command.
file -force -options ";exportSkels=auto;exportSkins=auto;exportUVs=1;exportColorSets=1;defaultMeshScheme=none;animation=0;eulerFilter=0;startTime=0;endTime=10;frameStride=1;frameSample=0.0" -type "USD Export" -pr -ea "D:\\skeleton_animation_test1.usd";

3 make a new empty scene
4 import the saved usd file.  select a mesh and see there is no skinning.

**Expected behavior**
I would expect skinned meshes to be saved in the usd file and import into Maya the same as they were exported.

**Attachments**
[skeleton_animation_test.zip](https://github.com/Autodesk/maya-usd/files/4847871/skeleton_animation_test.zip)

**Specs (if applicable):**
 Windows 10
Maya PR 115

**Comment by santosg87** [comment] 2020-07-06 19:38
hi @stevkalinowski thanks for reporting this. would you be able to send me your exported usd file to test? as far as I remember exporting should work for skinned geo jsut as expected. you might be seeing an issue with import. :)

**Comment by stevkalinowski** [comment] 2020-07-09 17:23
[skeleton_animation_test2.zip](https://github.com/Autodesk/maya-usd/files/4898421/skeleton_animation_test2.zip)

Here you go, this is what I get when exporting.  Thanks for looking into it.

**Comment by santosd** [comment] 2020-08-04 18:19
I took a look at this issue and was able to replicate it. In the USD file provided there is no skinning when I open it, so I re-skinned it. After exporting it and then re-importing it the skinning is lost.

**Comment by nielsvaes-es** [comment] 2021-01-20 11:01
Hi @santosg87 
Are there any updates on this? Trying in Maya 2020.4 and this still happens.

**Comment by eoffermann** [comment] 2021-02-24 22:58
Two comments for this issue:

1. For folks reproducing the issue in this ticket - there's a typo in the MEL in the original post. "exportSkins" is not a valid flag - it should read "exportSkin" - at least according to this https://github.com/Autodesk/maya-usd/blob/dev/plugin/pxr/doc/README.md

Since maya doesn't complain about errors inside an options string, you'd never know it was a problem in mel. The equivalent python raises an exception.

The original MEL would always result in an unskinned usd export (even if the skinning bug is fixed).

2. I notice that exporting a jointed/skinned character with animation that everything seems intact in usdview (the animation will play with skin bound to joints), but as reported in #603, when that usd returns to Maya, the joints are all at the origin and un-animated. Skinning seems ok, though, even if the resulting import is unusable due to the issue from #603

**Comment by santosg87** [comment] 2021-10-04 16:46
I believe we can close this issue. as noted, with the "exportSkin" option this is behaving as expected for me.

**Closed by santosg87** 2021-10-04 16:46 UTC
Labels: bug, reproduced
