### ISSUE TITLE
Draw*Purpose toggle attributes are not working with VP2.0 Render Delegate

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#261] opened 2020-02-07 21:29 UTC
**Describe the bug**
The automated test that tests drawing USD proxy shapes while changing their purpose-based draw attributes is currently failing when using the Viewport 2.0 Render Delegate. The code that exercises this test is [testDrawAndToggleDrawPurposeAttributes in the testProxyShapeDrawPurpose test](https://github.com/Autodesk/maya-usd/blob/ec6750b7b1311c474a857a0e78216c5dc16db93b/plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/testProxyShapeDrawPurpose.py#L70).

This test is part of a suite of tests that are run internally at Pixar. They are not included run as part of the external Pixar usdMaya plugin tests since they are making assumptions about the runtime environment that may not be valid for all users. However, moving forward, these tests should be run internally within Autodesk to validate correctness when testing any changes or fixes to the usdMaya plugin.

**Steps to reproduce**
1. Run the testProxyShapeDrawPurpose test

**Expected behavior**
The test passes with no errors.

**Comment by kxl-adsk** [comment] 2020-03-02 18:33
Since #285 is a duplicate of this issue, I'm closing this one as a duplicate (the other issue have easier steps for QA to reproduce).

**Closed by kxl-adsk** 2020-03-02 18:33 UTC
Labels: bug
