### ISSUE TITLE
Namespaces not working with USD file referenced as Maya reference

### ISSUE THREAD

**Issue by cescocm** [Autodesk/maya-usd#1691] opened 2021-09-09 07:40 UTC
**Describe the bug**
Trying to reference an USD file with the standard Maya reference system works but namespaces do not. Traceback is this:

// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/namespaceEditCmd.mel line 263: Cannot rename a read only node. // 
 
**Steps to reproduce**
1. Go to '.File - Create Reference'
2. Click on 'Choose a USD file'
3. Click on 'Use namespace'
4. Select 'Use selected namespace as parent and add new namespace string: ' and fill it with a string 'namespace'
5. Check error

**Expected behavior**
To work as with alembics or ma/mb files.

**Comment by santosd** [comment] 2021-09-13 21:19
I believe this is a duplicate of #1307, which has an issue logged for it internally with us. I am going to place this issue in the backlog along with the other GitHub Issue.

**Comment by santosg87** [comment] 2022-01-17 18:20
Closing this issue, as it seems to be a duplicate. we can track any changes on this work through #1307

**Closed by santosg87** 2022-01-17 18:20 UTC
Labels: bug, duplicate, import-export
