### ISSUE TITLE
Unit tests built with debug information crash Maya

### ISSUE THREAD

**Issue by elenadBlueSky** [Autodesk/maya-usd#271] opened 2020-02-10 22:55 UTC
I built the current maya-usd dev branch with debug information and ran the unit tests (in interactive Maya, under Linux).   When things got to the ProxyShape tests, Maya crashed with a Fatal Error message.  I tested in builds for both Maya 2019 and 2020 and the problem happens in both.

**The output:**
`[----------] 14 tests from ProxyShape
[ RUN      ] ProxyShape.basicProxyShapeSetUp
[       OK ] ProxyShape.basicProxyShapeSetUp (164 ms)
[ RUN      ] ProxyShape.basicTransformChainOperations
[       OK ] ProxyShape.basicTransformChainOperations (122 ms)
[ RUN      ] ProxyShape.basicTransformChainOperations2
maya.bin: /bluesky/design/users/elenad/dev/PACKAGES/maya-usd/plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeSelection.cpp:259: bool AL::usdmaya::nodes::ProxyShape::TransformReference::decRef(AL::usdmaya::nodes::ProxyShape::TransformReason): Assertion 'm_refCount' failed.
Stack trace: ... `

As you can see, the problem is in ProxyShapeSelection.cpp, line 259, where an _assert(m_refCount)_ statement fails.  I think an optimized build excludes assert statements, which is why this failure occurs only when the plugin is built with debug information.  But it seems important to investigate this rather than mask the error.  It will likely help uncover a real problem.

**Steps to reproduce**
- Start interactive Maya (or prompt mode could also work, but I haven't tried it)
- Load the AL_USDMayaTestPlugin.so plugin
- Run AL_maya_test_UnitTestHarness

**Comment by elenadBlueSky** [comment] 2020-02-11 14:15
Since I submitted the issue, I also tried this with Maya in prompt mode.  Same crash, same place (which makes sense, since it's the same assertion that's failing).

**Comment by kxl-adsk** [comment] 2020-02-11 19:37
@robthebloke Is this something you can comment on?

**Comment by kxl-adsk** [comment] 2020-03-02 18:41
@elenadBlueSky This looks to be duplicate of #236 - do you agree?

**Comment by elenadBlueSky** [comment] 2020-03-02 18:58
They do both have a "Assertion 'm_refCount' failed" message, so it does look like the same problem.

**Comment by kxl-adsk** [comment] 2020-03-02 18:59
Perfect, I will close this one as a duplicate.

**Closed by kxl-adsk** 2020-03-02 18:59 UTC
Labels: al, bug, question, unit test
