### ISSUE TITLE
USD Export Skel hard crash 100% repro

### ISSUE THREAD

**Issue by stevkalinowski** [Autodesk/maya-usd#958] opened 2020-12-01 23:06 UTC
**Describe the bug**
When exporting a usd file with a specific scene I am experiencing a crash.

**Steps to reproduce**
1. Open Sample Scene (I'll send to our AD rep)
2. Select the entire hierarchy of the node "root_GRP"
3. Execute this command in mel script editor
`file -force -options ";exportUVs=1;exportColorSets=1;defaultMeshScheme=none;defaultUSDFormat=usdc;animation=0;eulerFilter=0;startTime=1;endTime=1;frameStride=1;frameSample=0.0;parentScope=;exportDisplayColor=1;shadingMode=useRegistry;convertMaterialsTo=UsdPreviewSurface;exportInstances=1;exportVisibility=0;mergeTransformAndShape=1;stripNamespaces=0;materialsScopeName=materials;exportSkels=auto;exportSkins=auto" -typ "USD Export" -pr -es "c:\\treyarch_test.usd";`

4. Maya should crash with no Send Report option

**Expected behavior**
Don't crash

**Attachments**
Sent to Autodesk

**Specs (if applicable):**
 - OS - Windows 10 Pro
 - Maya PR120

**Comment by santosg87** [comment] 2021-01-04 15:08
@stevkalinowski I wasn't able to reproduce the crash 100% of the time. but i did see it happening. on the latest PR, this should be fixed are you able to give a try on your side to confirm, since this was crashing much more often for you? :)

cheers!

**Comment by stevkalinowski** [comment] 2021-01-04 22:17
Looks good so far.  I've tried at least 5 times on PR121 and it hasn't crashed yet.  Thanks!

**Comment by santosg87** [comment] 2021-01-05 17:18
awesome! thanks for the feedback! :)

**Closed by santosg87** 2021-01-05 17:18 UTC
Labels: bug
