### ISSUE TITLE
Selection highlight in viewport does not show up for prims added with "Add new prim" context menu action

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#2651] opened 2022-10-13 19:31 UTC
**Describe the bug**
A prim added using the "Add new prim" context menu action does not have the selection highlighted in the viewport. It appears to be selected in the Outliner, however, the highlight is not displayed in the viewport. If we try to re-select the object in the viewport or outliner, it does not appear.

It only appears after you move the prim and then, re-select it.

**Steps to reproduce**
1. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
2. Right click on the proxy shape -> Add new prim -> Capsule

Notice that the Capsule is selected in the outliner but it is not highlighted in the viewport.

**Expected behavior**
We would expect the selection highlight in the viewport to show up whenever a prim is selected. 

**Attachments**
![addprim_highlight_error](https://user-images.githubusercontent.com/12554015/195691965-a8a70b4c-4f93-431e-b299-f4aef94efaf4.gif)

**Specs (if applicable):**
- Linux
- maya2023.2
- Maya USD commit SHA [dev at 302f393]
- Pixar USD commit SHA [dev at 60ed06c]

Pixar Internal JIRA MAYA-3509

**Comment by stevattreyarch** [comment] 2022-10-13 20:47
I've been noticing this in the script editor when I select a model.  Unsure if it's related:

// Error: line 1: 'lead' is an unknown RGB display color name // 
// Warning: Failed to obtain selection highlight color for 'lead' objects //

**Comment by tanant** [comment] 2022-10-13 23:37
Weird.. I just tried in my setup (which admittedly is _crazy_ adhoc right now) and I wasn't able to replicate this in my 2022.3/0.19 and 2023.3/0.19 instances, on creation of the capsule I have it highlighted.

@stevattreyarch your setup looks basically like mine, to confirm, you got the same behaviour when doing the barebones new stage + make a capsule approach? FWIW, I also get the error message in 2022.3/0.19 (sort of occurs on select of anything in the USD tree)

**Comment by stevattreyarch** [comment] 2023-02-03 15:51
Hi, sorry for the long delay.  Yes, it was a barebones stage.  I'll try repro-ing again, it's been a bit so I'm not 100% sure how it came up initially.

**Comment by stevattreyarch** [comment] 2023-02-06 20:17
Ok, so I get the issue using USD Stage from File too, that's the workflow I was using originally.

I am confident the issue is because of the Pref viewport draw method "DirectX".  If I set to OpenGL Compatibility the issue is gone.

**Comment by gracekumagai** [comment] 2023-02-11 01:03
Hey @tanant, I tested this again today and I can no longer repro! 

I'm testing with:
- maya2023.2
- maya-usd commit sha (dev at abf29285)

**Comment by santosd** [comment] 2023-02-13 15:21
Thank you for confirming @gracekumagai, I will go ahead and close this one out.

**Closed by santosd** 2023-02-13 15:21 UTC
Labels: bug

**Comment by tanant** [comment] 2023-02-17 00:58
Brilliant, thanks!

**Comment by JRFK3D** [comment] 2023-11-17 21:00
Thanks for the help, just one more thing that helped to me, In the same tab, view section and the "WIREFRAME ON SHADED" option I didn't have check the reduced option, this last observation, no more (:

Good day
