### ISSUE TITLE
[EMSUSD-1801] Absolute path for `exportRoots` sets invalid defaultPrim 

### ISSUE THREAD

**Issue by BigRoy** [Autodesk/maya-usd#3991] opened 2024-11-08 08:24 UTC
**Describe the bug**

Supplying an `exportRoot` as a full path sets an invalid `defaultPrim` inside the exported USD file.

**Steps to reproduce**
1. Create a single root node (feel free to put underneath what you want)
2. Select the root node
3. Run this to export:
```python
from maya import cmds
cmds.mayaUSDExport(
    file="/path/to/export,usda",
    exportRoots=cmds.ls(selection=True, long=True)
)
```

**Expected behavior**

The `defaultPrim` will be written as:
```
defaultPrim = "|prop_flower"
```
But should be:
```
defaultPrim = "prop_flower"
```

⚠️ This is a regression because it worked before.

Maya 2024.2 with 0.25.0 exports the correct default prim path.
Maya 2025.3 with 0.30.0 exports the invalid default prim path.

**Attachments**
If applicable, add screenshots, sample files, etc to help explain your problem.

**Specs (if applicable):**
 - OS & version: Windows 10
 - Compiler & version: ??
 - Maya version: Maya 2025.3
 - Maya USD: 0.30.0

**Additional context**

n/a

**Comment by santosd** [comment] 2024-11-12 22:26
Hi @BigRoy, we discussed this issue internally and we will be taking a look at it. Thank you for reporting this regression.

**Comment by santosd** [comment] 2024-11-19 22:35
Hi @BigRoy it seems that this issue was recently fixed with the following PR: https://github.com/Autodesk/maya-usd/pull/3993
I have tested it on my end and it seems to be working as expected now. You can test on your end by building the latest code of Maya USD. However, if you are not able to do that, the next release will have this fix in it. I will go ahead and close this ticket our for now, but let us know if you have any questions.

**Closed by santosd** 2024-11-19 22:35 UTC
Labels: bug, reproduced
