### ISSUE TITLE
[MAYA-107682] usdz export writes incorrect texture paths

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#972] opened 2020-12-04 20:33 UTC
**Describe the bug**

This is an issue that builds on https://github.com/Autodesk/maya-usd/issues/795.

The resulting usdz file now does contain the texture, but it now contains the entire full path hierarchy to the file instead.
See this screenshot showing the usdz files hierarchy. Note, this could potentially be revelatory for certain people if the hierarchy included project names etc...

The usdz file is attached : 
[asset.usdz.zip](https://github.com/Autodesk/maya-usd/files/5645328/asset.usdz.zip)

 
![image](https://user-images.githubusercontent.com/4443090/101211216-a84c5300-362b-11eb-9ede-9f07e2377535.png)

The resulting usd file inside the usdz also does not point to the correct texture path, instead pointing to the path as it was in the Maya file. 

```python
def Shader "file1"
{
    uniform token info:id = "UsdUVTexture"
    asset inputs:file = @../sourceimages/checkerboard.png@
}
```

The workaround of disabling the block of code mentioned in https://github.com/Autodesk/maya-usd/issues/795 works to let us workaround this behaviour.

While the change in the https://github.com/Autodesk/maya-usd/pull/865 partially fixed the original issue so the texture is included, it actually creates a different issue as described here. Apologies for not catching this sooner, as the change in the PR did satisfy a specific part of our pipeline that obscured the second part of this issue. Testing in a fully vanilla environment exposes this next bit which is still problematic.

**Steps to reproduce**
1. Open Maya project from https://github.com/Autodesk/maya-usd/issues/795
2. Export usdz file
3. Expand the usdz file and look at the resulting file and USD texture reference path as described above.

**Expected behavior**
I would expect the texture to be written such that it's using the same relative path as the maya material does, just inlined into the Maya file.
If the texture lives outside the Maya workspace, then it would be best to keep the old behaviour where it was stored in `0/textureName.jpg` etc....

**Specs (if applicable):**
 - macOS Catalina and Big Sur
 - Compiler version: Apple clang version 12.0.0 (clang-1200.0.32.5) (reproducible on older clang versions too)
 - Maya 2018.5 and 2020.0
 - Maya USD commit SHA ddcd319b7785a8cc586b3106ecd16cba25f9cb3c
 - Pixar USD commit SHA d8a405a1344480f859f025c4f97085143efacb53

**Comment by JGamache-autodesk** [comment] 2020-12-07 14:27
Are you using the `compatibility='appleArKit'` export option? If not, does it fix this issue when you do?

**Comment by dgovil** [comment] 2020-12-07 17:01
@JGamache-autodesk I did try that, but it didn't change the results. Still the same issue unfortunately

**Comment by JGamache-autodesk** [comment] 2020-12-07 17:55
I am not able to reproduce the issue you are having. Could you expand on how you export the scene by pasting the Maya command that was used for step 2?

**Comment by dgovil** [comment] 2020-12-07 18:44
Sure, so I did a fresh build from
 345ab28f8ae0d08d6e0f50df79b9e944a9788d40 

Maya Workspace: [bugreports.zip](https://github.com/Autodesk/maya-usd/files/5654563/bugreports.zip)

Little diagnostic script that exports the file, then prints out the usdz contents and then the texture file path

```python
from maya import cmds
import zipfile
import os
from pxr import Usd
from pxr import UsdShade


path = os.path.join(os.path.dirname(cmds.file(q=True, sn=True)), "asset.usdz")

# Write the file out
cmds.mayaUSDExport(
    f=path,
    exportSkels="auto",
    frameRange=(1,100),
    compatibility='appleArKit'
)

# List the zipfile hierarchy
with zipfile.ZipFile(path) as zf:
    zf.printdir()
    
# Check with USD what the path is
stage = Usd.Stage.Open(path)
prim = stage.GetPrimAtPath("/AssetGroup/Looks/pxrUsdPreviewSurface1SG/file1")
shader = UsdShade.Shader(prim)
tex = shader.GetInput("file").Get()

print(tex)

```


And the output when run.

The last line shows the texture path on the file prim. This almost matches the Maya workspace except it adds the `..` prefix.
To be correct, it should be something like `@Users/dhruvgovil/Documents/maya/projects/bugreports/sourceimages/checkerboard.png@`assuming the current texture path in the usdz.

The second last line shows the path to the actual texture in the usdz. Previously, this would be in a numerical directory within the zip. e.g. the path would have been: `0/checkerboard.png` instead. The numerical directory itself isn't important other than preventing collisions in texture names.

```
File Name                                             Modified             Size
asset.usdc                                     2020-12-07 10:39:12         2859
Users/dhruvgovil/Documents/maya/projects/bugreports/sourceimages/checkerboard.png 2020-09-23 14:31:38        68309
@../sourceimages/checkerboard.png@
```

**Comment by dgovil** [comment] 2020-12-07 22:38
Okay, so I was running through a debugger, and it seems like the issue may be that the extension type check that is there is getting the incorrect value?

![image](https://user-images.githubusercontent.com/4443090/101413742-a5569a00-3899-11eb-9a3f-58f81b633543.png)

If I understand the intention here...this block is only meant to run for `usda/usdc` files, and skip if it's a usdz. However since it's picking up as a usdc extension, it's running and therefore creating the incorrect usdz file?
`if (fileExt != UsdMayaTranslatorTokens->UsdFileExtensionPackage)`

**Comment by santosg87** [comment] 2020-12-08 04:44
@JGamache-autodesk I am able to reproduce this issue internally as well. we have a Jira item logged for it already.

**Comment by JGamache-autodesk** [comment] 2020-12-14 14:43
This bug was reproduced on OS/X, but not on Windows and Linux where the texture path is correct: `@0/checkerboard.png@`. I will have to find out why OS/X requires a two-step export.

**Comment by dgovil** [comment] 2020-12-22 23:24
(I know y'all are out for a well earned holiday break, but posting here before I forget)

Just doing some digging, but in `writeJob.cpp` in `_BeginWriting` there's this (condensed) code block:

```cpp
if (fileExt == UsdMayaTranslatorTokens->UsdFileExtensionPackage) {
        // We don't write to fileNameWithExt directly; instead, we write to
        // a temp stage file.
        _fileName = _MakeTmpStageName(TfGetPathName(fileNameWithExt));
}
```

`_MakeTmpStageName` always picks the `.usdc` extension. I don't see any platform specific code up till this point, so it should happen on win/linux too from a quick skimming of the code.

I'm going to try and put the original file name into the ExportArgs for retrieval later, since I don't see any where that it is accessible otherwise

**Comment by dgovil** [comment] 2020-12-23 02:22
I've opened a PR for the fix: https://github.com/Autodesk/maya-usd/pull/1028

**Comment by kxl-adsk** [comment] 2021-01-07 12:15
PR #1028 has been merged. @santosg87 please validate and close this issue.

**Closed** 2021-06-14 20:37 UTC
Labels: bug, confirmed
