### ISSUE TITLE
[MAYA-121936] Selection Issue: Picking models behind the camera

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1946] opened 2022-01-04 16:56 UTC
**Describe the bug**
Sometimes picking in the viewport chooses models behind the camera. It seems to be rays that if continued behind the camera would intersect those objects. 

Also, to reproduce, it requires a second on-screen instance of the model. It also seems related to the instanceable state of the models as the models need to be set to instanceable to reproduce.

**Steps to reproduce**
Overall, if there is a model set to instanceable in the viewport with duplicates of that model behind the camera, selecting in the viewport can select the models behind the camera.

1. Open `kitchen_set_instanced`
2. Make 3 duplicates of `Kitchen_set_instanced_original|Kitchen_set_instanced_originalShape,/Kitchen_set/Props_grp/North_grp/FridgeArea_grp/Refridgerator_1`
3. Position duplicates behind the camera:
3a. Position 1st duplicate at translateX = 100, translateY = -600
3b. Position 2nd duplicate at translateX = 200, translateY = -600
3c. Position 3rd duplicate at translateX = 300, translateY = -600
4. Move the perspective camera to tx = 180, ty = -550, tz = 90, rx = 90
5. Click around in the viewport (around the chair in front of the original fridge). Notice that the fridges behind the camera are selected instead of the chair or nothing.

I also hid the background models in the kitchen_set_instanced and moved the fridges to the root in the gif to make it easier to reproduce / visualize.

**Expected behavior**
We would expect it not to select models behind the camera.

**Attachments**
![selection_issue_autodesk](https://user-images.githubusercontent.com/12554015/148094636-7066b49f-cb75-4ae4-bcf7-cc24fde09a08.gif)

**Specs (if applicable):**
 - OS (Linux 64 bit)
 - Maya 2022.update3

**Comment by williamkrick** [comment] 2022-01-04 18:45
Hi @gracekumagai,

I think this is probably a duplicate of https://github.com/Autodesk/maya-usd/issues/1587 which I believe we've fixed in the most recent Maya Preview Release.

**Comment by dj-mcg** [comment] 2022-01-04 20:59
Thanks @williamkrick - will this be backported to 2022?

Logged internally as Pixar Jira MAYA-3182

**Comment by gracekumagai** [comment] 2022-02-28 22:01
Thanks @williamkrick! I tested this on our end and it seems to be working as expected. 

I wanted to follow up on Dan's question - what is the feasibility of this fix being backported to 2022? Thanks!

**Comment by santosd** [comment] 2022-03-11 17:58
The backport of this issue is being worked on.

**Comment by gracekumagai** [comment] 2022-05-24 19:26
Hey @santosd, I tested in 2023 and it seems to be resolved :) Feel free to close this ticket out if it's not needed on your end!

**Comment by santosd** [comment] 2022-05-26 14:02
Thank you Grace, closing this out.

**Closed by santosd** 2022-05-26 14:02 UTC
Labels: bug
