### ISSUE TITLE
Installing MayaUSD 0.29.0 for Maya 2024.2 Breaks LookdevX 1.2 in Wndows 11

### ISSUE THREAD

**Issue by markainslie** [Autodesk/maya-usd#3885] opened 2024-08-08 19:06 UTC
**Description**
Installing MayaUSD 0.29.0 prevents LookdevXMaya.mll from loading in Windows Maya 2024.2.

**Steps to reproduce**
1. Run Maya 2024.2 with MayaUSD  0.28.0
2. Load LookdevXMaya.mll in the Plug-in Manager - the plugin loads.
3. Quit Maya and install MayaUSD 0.29.0.
4. Run Maya and try to load LookdevXMaya.mll in the Plug-in Manager again. It fails to load.
5. Error below:
``
// Error: file: C:/Program Files/Autodesk/Maya2024/scripts/others/pluginWin.mel line 316: Unable to dynamically load : C:/Program Files/Autodesk/LookdevX/Maya/2024/1.2.0/plug-ins/lookdevx/plug-ins/LookdevXMaya.mll
// The specified module could not be found.
// Error: file: C:/Program Files/Autodesk/Maya2024/scripts/others/pluginWin.mel line 316: The specified module could not be found.
//  (LookdevXMaya)
``
6. Reinstall MayaUSD 0.28.0 and everything works as expected.

**Expected behavior**
LookdevXMaya.mll needs to load.

**Specs:**
 - Windows 11
 - Maya 2024.2
 - MayaISD 0.29.0
 - LookdevX 1.2

**Comment by wallworm** [comment] 2024-08-09 13:38
Thank you for reporting this.

Unfortunately, when we released the initial version of LookdevX in Maya 2024, it had some dependencies that made it prone to breaking with changes in Maya USD. We don't have a current path for updating LookdevX in Maya 2024; at this time the only solution is to stay on Maya USD 0.28 if you need LookdevX. Note this issue only pertains to Maya 2024.

I know it's not an ideal answer, but it's where we are today. We've taken steps to remove the root causes of this in later versions of LookdevX.

**Comment by santosg87** [comment] 2024-09-16 13:52
closing this issue for now, as we don't plan on fixing current versions of lookdevX+MayaUSD builds.

**Closed by santosg87** 2024-09-16 13:52 UTC
Labels: bug
