### ISSUE TITLE
Performance issue when selecting prim with large number of children

### ISSUE THREAD

**Issue by csyshing** [Autodesk/maya-usd#1004] opened 2020-12-15 03:37 UTC
**Describe the bug**

Hi,

We are using **UFE/proxyRenderDelegate** build of mayaUsd plugin and found a performance issue when selecting a top level prim with large number of children, e.g. a super big environment set in a shot.

We noticed that the call was from [proxyRenderDelegate.cpp#L147-148](https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp#L147-L148) which the scene delegate always traverses into the hierarchy, this really slows down a lot for big environment.

Is there anything can be done in `maya-usd` to improve the performance? Thanks.

**Steps to reproduce**

I am not able to share the production shot but this issue is reproducible with any USD file.

1. Load mayaUsd plugin and open any USD file, e.g. Pixar's kitchen set.
2. Turn on the TF DEBUG symbol to observe the behavior:
```
import pxr
pxr.Tf.Debug.SetDebugSymbolsByName("USDIMAGING_SELECTION", True)
```
3. Run Python code snippet below to select the prim **/Kitchen_set/Arch_grp** in kitchen set:
```
import ufe

# construct an UFE path for Arch_grp:
UFE_MAYADG_RUNTIME_NAME = "Maya-DG"
UFE_MAYAUSD_RUNTIME_NAME = "USD"
mgr = ufe.RunTimeMgr.instance()
mayaDgRunTimeId = mgr.getId(UFE_MAYADG_RUNTIME_NAME)
mayaUsdRunTimeId = mgr.getId(UFE_MAYAUSD_RUNTIME_NAME)

mayaDgSegment = ufe.PathSegment('|world|Kitchenset|KitchensetShape', mayaDgRunTimeId, "|")
mayaUsdSegment = ufe.PathSegment(str('/Kitchen_set/Arch_grp'), mayaUsdRunTimeId, "/")
mayaUsdUfePath = ufe.Path([mayaDgSegment, mayaUsdSegment])

# append the selection item
newSelection = ufe.Selection()
newSelection.append(ufe.Hierarchy.createItem(mayaUsdUfePath))

# select the prim Arch_grp:
sel = ufe.GlobalSelection.get()
sel.replaceWith(newSelection)
```
4. From console output, it shows that `PopulateSelection` recursively traverses into all children:
```
PopulateSelection: (prim) /Proxy_KitchensetShape_0x1538cc60/Kitchen_set/Arch_grp/Kitchen_1/Geom/Cabinets/Body/pCube251
PopulateSelection: (prim) /Proxy_KitchensetShape_0x1538cc60/Kitchen_set/Arch_grp/Kitchen_1/Geom/Cabinets/Body/pCube277
PopulateSelection: (prim) /Proxy_KitchensetShape_0x1538cc60/Kitchen_set/Arch_grp/Kitchen_1/Geom/Cabinets/Body/pCube278
...
...
PopulateSelection: (prim) /Proxy_KitchensetShape_0x1538cc60/Kitchen_set/Arch_grp/Kitchen_1/Geom/Windows_Frame/WindowStill/Window_Frame_Arch/pCube79
PopulateSelection: (prim) /Proxy_KitchensetShape_0x1538cc60/Kitchen_set/Arch_grp/Kitchen_1/Geom/Windows_Frame/WindowStill/Window_Frame_Arch/pCylinder217
PopulateSelection: (prim) /Proxy_KitchensetShape_0x1538cc60/Kitchen_set/Arch_grp/Kitchen_1/Geom/Windows_Frame/pCube421
```

**Expected behavior**
Any improvement is appreciated.

**Specs (if applicable):**
 - OS & version: Centos 7.4
 - Compiler & version: gcc 6.3.1
 - Maya version: Maya 2020
 - Maya USD commit SHA: v0.5.0 [dev at 62037f3] UFE/proxyRenderDelegate build
 - Pixar USD commit SHA: official tagged version 19.11 and 20.11

**Comment by HdC-adsk** [comment] 2020-12-16 19:30
@csyshing Thanks for reporting the issue. Do you test USDView for the same workflow? How does its performance look like?

**Comment by csyshing** [comment] 2020-12-17 09:32
Good question.... I just tried in usdview and it's behaving the same :-(
I was thinking, maybe there are some optimizations can be done in Maya because proxyRenderDelegate is inherited from MPxSubSceneOverride?

**Comment by HdC-adsk** [comment] 2020-12-17 11:45
@csyshing Thanks for confirming. Both USDView and VP2RenderDelegate having the same bottleneck here makes sense to me because `PopulateSelection` should be required by all Hydra render delegates in order to traverse all the children rprims under the root. So my suggestion is to ask the question in usd-interest forum and see if there is any suggestions on the scene graph, e.g. does it help if we make the scene graph flattened? is there something that can be done in Hydra to remove the bottleneck?

**Comment by csyshing** [comment] 2020-12-17 22:56
Thanks @HdC-adsk . I will ask in usd-interest then, cheers!

**Comment by kxl-adsk** [comment] 2020-12-18 01:59
Closing since the issue is related to USD. @csyshing feel free to add a link to the usd-interest discussion in case someone runs into the same problem.

**Closed by kxl-adsk** 2020-12-18 01:59 UTC
Labels: bug, vp2renderdelegate
