### ISSUE TITLE
CXX ABI detection is broken

### ISSUE THREAD

**Issue by abbec** [Autodesk/maya-usd#3560] opened 2024-01-16 15:09 UTC
**Describe the bug**
When detecting the [CXX abi](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html) in `FindMaya.cmake`, the code uses libFoundation, which in the shipped version of Maya, has symbols stripped. 

This causes maya-usd against Maya2024 to be incorrectly built using the old cxx abi (since it falls back to the old abi by default).

The error in the code is [here](https://github.com/Autodesk/maya-usd/blob/ce0a3bb027fec777bfe712a73c31037e78e5d382/cmake/modules/FindMaya.cmake#L481) since the expectation that `libFoundation.so` contains symbols is not true.

**Steps to reproduce**
```
$ nm /usr/autodesk/maya2022/lib/libFoundation.so
nm: /usr/autodesk/maya2022/lib/libFoundation.so: no symbols
```

**Expected behavior**
Maya 2024 is detected to be using the new ABI and 2022 is detected to use the old ABI.

**Comment by seando-adsk** [comment] 2024-01-16 18:27
Ah sorry about that. We are missing the nm flag `-D` to see the dynamic symbols. I'll get a pull-request opened to fix this.

**Comment by seando-adsk** [comment] 2024-01-17 14:38
@abbec This should be fixed by #3562. Can you try using the latest source from the dev branch and let me know if the problem is fixed.

Thanks, Sean

**Comment by seando-adsk** [comment] 2024-01-17 14:45
I ran the `nm -D` command on a Maya install and it did work.  You could just try running this command:
` nm -D libFoundation.so | grep findVariableReplacement | grep " T "` and see if you get any output.

**Comment by abbec** [comment] 2024-01-17 16:16
```
$ nm -D /usr/autodesk/maya2022/lib/libFoundation.so | grep findVariableReplacement | grep " T "
<no output>
$ nm -D /usr/autodesk/maya2024/lib/libFoundation.so | grep findVariableReplacement | grep " T "
00000000002b9970 T _ZN16TMayaEnvironment23findVariableReplacementERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by seando-adsk** [comment] 2024-01-17 16:37
Perfect that is expected. So for Maya 2024 it will detect that it was built with the new cxx ABI and build MayaUsd with the appropriate flag.

Sean

**Comment by abbec** [comment] 2024-01-17 17:11
Sure, but won't 2022 (and 2023) be indecisive. I.e. the check could just as well be `version >= 2024`?

**Comment by seando-adsk** [comment] 2024-01-17 17:17
The default value is to not build with cxx abi, as seen [here](https://github.com/Autodesk/maya-usd/blob/dev/cmake/modules/FindMaya.cmake#L475).

The nm output for those earlier Maya's will be empty so that is caught by the test [here](https://github.com/Autodesk/maya-usd/blob/dev/cmake/modules/FindMaya.cmake#L490) and the default value will be used.

Sean

**Comment by abbec** [comment] 2024-01-17 17:31
I guess what I am saying is that if Maya 2022.6 in the future is built with the new abi, the nm output would still be empty and the detection would wrongfully assume that it should use the old abi. If the new abi is never used for versions < 2024 then this is not a problem.

**Comment by santosg87** [comment] 2024-01-31 22:56
@abbec is it ok to close this issue now?

**Comment by abbec** [comment] 2024-01-31 23:11
Yep, thanks :)

**Closed** 2024-02-01 14:30 UTC
Labels: bug
