### ISSUE TITLE
[MAYA-114992] Some Skinning broken after USD Export and Import

### ISSUE THREAD

**Issue by stevkalinowski** [Autodesk/maya-usd#1821] opened 2021-11-09 20:37 UTC
**Describe the bug**
After a usd file has been exported using a complex skeleton such as a character, some of the skinned objects become either deformed incorrectly or are floating in space not in their original position.

**Steps to reproduce**
1. Open the scene "character_export.ma" (provided previously as an example scene)
2. Export All, choose USD as the type
3. Use None for sub-div, Skinning and Skeletons set to Auto
4. File > New for a clean scene
5. File > Import and choose the exported usd file

**Expected behavior**
The mesh and skeleton should import back in exactly the same.

**Attachments**
Before export screenshot and issues in the After Import screenshot.

![skinningExportImportIssue_Before](https://user-images.githubusercontent.com/64916304/141000626-1410fddb-037e-4486-abec-8cf88ef1c5c6.png)

![skinningExportImportIssue_After](https://user-images.githubusercontent.com/64916304/141000641-0e86a625-163d-4a9e-b687-8df04a183c53.png)

**Specs (if applicable):**
 - OS Windows 10
 - Maya 2022.2.1
 - Maya USD 0.13.0

**Additional context**
Please reach out to me for the example scene if I need to re-upload it.

**Comment by wtelford** [comment] 2021-11-22 19:14
Hey @santosd can you log this internally?

**Comment by santosd** [comment] 2021-11-24 16:36
Logged internally as MAYA-114992.

**Comment by santosg87** [comment] 2022-06-08 17:24
@stevkalinowski is this one still a problem? is it ok to close this issue? :)

**Comment by stevattreyarch** [comment] 2022-06-08 19:04
It's still broken in PR134.  I'm not sure if the fix is included in there, I thought someone told me it wasn't in the beta just yet, so I was waiting.

**Comment by stevattreyarch** [comment] 2022-06-08 19:06
I'm stevkalinowski, I cannot access that other github account anymore.

**Comment by santosg87** [comment] 2022-06-20 18:27
@santosd are you able to test and see if the issue is still present on your side?

**Comment by santosd** [comment] 2022-09-12 19:00
We implemented a fix for this and the issue was tested and closed internally. Closing this for now unless @stevattreyarch is still having the issue. @stevattreyarch can you confirm with the latest?

When I initially validated it was in Maya PR 133 2022-04-26-0315 using Maya USD 0.18.0:

Checked the same workflow as before. The file now imports better as explained in the comment from William. Here are my results on a fresh export\import: 
![image](https://user-images.githubusercontent.com/29235905/189734322-34a6be76-b0a1-4276-8cc2-d81017988c05.png)

**Closed by santosd** 2022-09-12 19:00 UTC
Labels: bug

**Comment by stevattreyarch** [comment] 2022-09-22 20:34
Confirmed fixed on 0.19.0.  Thanks!

**Comment by santosd** [comment] 2022-09-23 14:03
Awesome! Thanks for confirming @stevattreyarch .
