### ISSUE TITLE
Maya fatal error upon import of any usd file

### ISSUE THREAD

**Issue by liorbenhorin** [Autodesk/maya-usd#433] opened 2020-04-15 16:31 UTC
Hello!,
After successful load of the mayaUsdPlugin and pxrUsd ,any attempt to import a usd file is followed by Maya fatal crash.

Using the import methods from both mayaUsdPlugin and pxrUsd yields the same crash.
Building with 2019 devkit and 2019 update 2 devkit yields the same crash.

![image](https://user-images.githubusercontent.com/18227469/79362699-94929600-7f4f-11ea-87e1-c92a0e4a9f08.png)

//=====================================================
Maya Crash Report
//=====================================================

Exception code: 80000003: BREAKPOINT 
Fault address:  A08FD162 in C:\WINDOWS\System32\KERNELBASE.dll
0001:000BC162 Logical offset (see .map file for location)

Call stack:
End of stack

//crash log file name = C:\Users\liorbh\AppData\Local\Temp\MayaCrashLog200415.1857.log
//version     = 19.2.0.8774
//cut            = Tue 07/02/2019, 201907021628
//current scene = unDisclosed
//command history (most recent last):
//====================================================
//last tool: renderWindowSelectContextItem
//====================================================
//panel with focus: modelPanel4
//visible panels:
// modelPanel4 outlinerPanel1 
//====================================================
//Memory usage:
// 49122.301 Mb	Free Memory
// 88302.609 Mb	Free Swap
//  968.602 Mb	Current

//====================================================

maya-usd build log
D:\development\USD_DEV\maya-usd>python build.py --generator Ninja --maya-location C:/Program Files/Autodesk/Maya2019 --pxrusd-location D:/development/USD_DEV/build/USD --devkit-location D:/development/USD_DEV/maya-devkit-update2 --build-args="-DCMAKE_MAKE_PROGRAM=D:/development/USD_DEV/ninja/ninja.exe"

    Building with settings:
      Source directory          D:\development\USD_DEV\maya-usd
      Workspace directory       D:\development\USD_DEV\maya-usd\Files\Autodesk\Maya2019
      Build directory           D:\development\USD_DEV\maya-usd\Files\Autodesk\Maya2019\build\RelWithDebInfo
      Install directory         D:\development\USD_DEV\maya-usd\Files\Autodesk\Maya2019\install\RelWithDebInfo
      Variant                   RelWithDebInfo
      Python Debug              Off
      CMake generator           Ninja
      Build Log                 D:\development\USD_DEV\maya-usd\Files\Autodesk\Maya2019\build\RelWithDebInfo\build_log.txt
      Build arguments           ['-DCMAKE_MAKE_PROGRAM=D:/development/USD_DEV/ninja/ninja.exe']
      Stages arguments          ['clean', 'configure', 'build', 'install']
Success MayaUSD build and install !!!!
Elapsed time: 00:04:20

[build_log.txt](https://github.com/Autodesk/maya-usd/files/4482378/build_log.txt)

AL_USDMayaPlugin does load, with an error:
// Error: IsA() was given an Unknown base type.  This probably means the attempt to look up the base type failed.  (Note: to explicitly check if a type is unknown, use IsUnknown() instead.) -- Runtime Error in IsA at line 782 of D:\development\USD_DEV\USD-20.02\USD\pxr\base\tf\type.cpp // 
about 100+ lines like these...

 - Windows 10
 - Microsoft Visual Studio 2019
 - Maya 2019.2
 - Maya USD commit v0.1.0 / 00d651a 
 - Pixar USD commit v20.02 / be1a80f

UPDATE:

Running the build on the 'tests' stage also causes a Maya crash:
![image](https://user-images.githubusercontent.com/18227469/79371137-8a2ac900-7f5c-11ea-8271-05c6c1a40f47.png)

I think the log have some useful info in it...
[build_log.txt](https://github.com/Autodesk/maya-usd/files/4482931/build_log.txt)

**Comment by santosd** [comment] 2020-04-17 15:20
Hi @liorbenhorin, Thank you for reporting this issue. One of our developers tried this out in a similar environment (builds and OS) and they were not hitting the fatal error you are seeing. Did you by chance submit the CER (Crash Error Report)? If so please provide me the number or the email you used to submit it and I can take a look to see if it helps us determine what the cause might be.

**Comment by Sushant304** [comment] 2020-04-17 19:12
Hi there 
I am also trying to build but i got this error
 C:/boost/lib/cmake/boost_filesystem-1.70.0/boost_filesystem-config.cmake

  but it set boost_filesystem_FOUND to FALSE so package "boost_filesystem" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.
So could me help me with that

**Comment by liorbenhorin** [comment] 2020-04-18 13:31
Hey @santosd  - Unfortunate im still getting the crash after several more attempts to build.
Here is a CER that i submitted just now **217889116**.

Includeing bothe build logs for pixar usd and for maya-usd
[maya-usd build_log.txt](https://github.com/Autodesk/maya-usd/files/4496691/build_log.txt)
[pixar USD log.txt](https://github.com/Autodesk/maya-usd/files/4496692/log.txt)

Thanks for any help

**Comment by Sushant304** [comment] 2020-04-18 13:41
May i ask you a favor. Could you please share me how you build the core USD
and the Maya -USD

**Comment by liorbenhorin** [comment] 2020-04-18 13:58
@Sushant304  sure:

for core USD:

from x64 Native tools command prompt for VS 2017
with Python 2.7.12 in the PATH, with PySide PyOpenGL PyOpenGL_accelerate Jinja2 installed

``python build_scripts\build_usd.py "D:\development\USD_DEV\pixar\build\USD" --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem" USD,"-DPXR_BUILD_TESTS=ON"``

for maya-usd

from x64 Native tools command prompt for VS 2017
with Python 2.7.15 in the PATH, with PySide PyOpenGL PyOpenGL_accelerate Jinja2 installed
(bumped python version as per [https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md]())

``python build.py --generator Ninja --stages clean,configure,build,install,test  --maya-location C:/Program Files/Autodesk/Maya2019 --pxrusd-location D:/development/USD_DEV/pixar/build/USD --devkit-location D:/development/USD_DEV/maya/2019 --build-args="-DCMAKE_MAKE_PROGRAM=D:/development/USD_DEV/ninja/ninja.exe"``

**Comment by Sushant304** [comment] 2020-04-18 14:21
Boost version and CMake version.

**Comment by liorbenhorin** [comment] 2020-04-18 16:07
@Sushant304 
Cmake 3.16.5
boost is being downloaded and built automatically by core usd, and is set to 1.65.1 (I know, that maya-usd requirements ask for 1.70.0, but i could not get the core usd to build with it...)

**Comment by santosd** [comment] 2020-04-21 14:09
Hello @liorbenhorin,

Thank you for providing me the CER, unfortunately it didn't provide many clues as to where the issue is. I am thinking it is possible that there is an issue with the build itself. Could you try using the build from our [releases](https://github.com/Autodesk/maya-usd/releases) page. The 0.1.0 version should be the one that would work on your end. Let me know if that works for you.

**Comment by kxl-adsk** [comment] 2020-11-05 22:32
Closing this issue since there was no new activity for a long time.

**Closed by kxl-adsk** 2020-11-05 22:32 UTC
Labels: bug, question
