### ISSUE TITLE
Instancer that uses a ProxyShape as its master fails to draw in VP2.0

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#264] opened 2020-02-07 23:29 UTC
**Describe the bug**
Pixar's test that tried to draw a instancer that uses a ProxyShape as its master fails when running with the Viewport 2.0 Render Delegate.

**Steps to reproduce**
1. Run testPxrUsdMayaGLInstancerDraw test
2. Observe that the instancer fails to draw in the output of the test

**Expected behavior**
The instancer draws as expected

**Additional context**
The current implementation if the instancerImager expects to be working with the HdImagingShape, but that node is not reigstered when the Viewport 2.0 render delegate is enabled.

This test is part of a suite of tests that are run internally at Pixar. They are not included run as part of the external Pixar usdMaya plugin tests since they are making assumptions about the runtime environment that may not be valid for all users. However, moving forward, these tests should be run internally within Autodesk to validate correctness when testing any changes or fixes to the usdMaya plugin.

**Comment by HdC-adsk** [comment] 2020-02-28 17:29
@dj-mcg Thanks for reporting this issue. To help me understand better, does pxrUsdProxyShape already support Maya DAG instancing? I just had a quick test here by duplicating the pxrUsdProxyShape using DAG instances. And it doesn't seem to work. Is the test you described using DAG instancing or some other instancer?

**Comment by dj-mcg** [comment] 2020-02-28 17:41
Sorry @HdC-adsk - I should have been more clear - the 'Instancer' I'm referring to here is actually a _Point_ Instancer that is using a ProxyShape as it's prototype, as opposed to a Maya or USD instance. If you have a peek at the test I referenced it may explain things more explicitly

Sorry I was unclear! Thanks for looking into it.

**Comment by HdC-adsk** [comment] 2020-02-28 18:03
Ok, it is using particle instancer. Is that the workflow you use in production instead of the DAG instancing? Thanks.

**Comment by dj-mcg** [comment] 2020-02-28 18:39
@HdC-adsk The test that is failing here specifically exercises the Point Instancer workflow that we use in production. We don't expect the USDMaya transition to require a change in our production workflows, which is why it's important that this tests continues to pass.

Thanks so much!

**Comment by HdC-adsk** [comment] 2020-02-28 18:41
Makes sense. Thanks a lot for the info.

**Comment by santosd** [comment] 2020-03-25 14:39
Tested this on my end using the InstancerDrawText.ma file that the script refers to and I noticed that that particle instancing is not currently supported with USD because Maya doesn't understand what the usd node is it will not add it to the instancer and when the top transform node is added, it shows up in the instancer, but it does not draw anything in VP2. This also doesn't draw in Hydra, but I am guessing that is expected. I am going to mark this with the "unit test" label to assure that we move this test over to the Maya USD side so that we can assure that it is passing so no workflow changes have to occur.

**Comment by HdC-adsk** [comment] 2020-03-25 16:08
@santosd Thanks for validation. Based on the above comment, shall we remove the vp2RenderDelegate label because we don't need workflow change?

**Comment by mattyjams** [comment] 2020-03-25 18:31
Hey @santosd and @HdC-adsk! Sorry, but I'm not quite following the results you're seeing on your end.

If you open the [InstancerDrawTest.ma](https://github.com/Autodesk/maya-usd/blob/dev/plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/InstancerDrawTest/InstancerDrawTest.ma) scene file using the Pixar batch renderer (`VP2_RENDER_DELEGATE_PROXY=0`), you definitely should see something in the viewport with Viewport 2.0. We'd expect it to produce images like this one (or the others in the same directory):

https://github.com/Autodesk/maya-usd/blob/dev/plugin/pxr/maya/lib/pxrUsdMayaGL/testenv/InstancerDrawTest/baseline/InstancerTest_initial.png

We had to write code specifically for that, to translate Maya-native point instancers (in the case of this test, an `nParticle` node) into UsdGeomPointInstancers to be imaged by Hydra. There's no DAG instancing in play here.

Most of the relevant code for that is here:
https://github.com/Autodesk/maya-usd/blob/dev/lib/render/pxrUsdMayaGL/instancerShapeAdapter.h#L38
https://github.com/Autodesk/maya-usd/blob/dev/lib/render/pxrUsdMayaGL/instancerImager.h#L38

The issue we're seeing is that when using the VP 2.0 render delegate (`VP2_RENDER_DELEGATE_PROXY=1`), we do **not** see anything in the viewport. If by setting the viewport to "Hydra" you mean using mayaToHydra, then I'm not actually sure what you'd see, but I'd bet you probably don't see anything drawn there either.

Does that make sense? Let me know if you're seeing something different.

**Comment by santosd** [comment] 2021-11-04 19:33
@gracekumagai I wanted to get ahold of you on this one, as I have been testing it using the steps that Matt had provided previously, but I have not been able to get the result with the instanced cubes. I have tried disabling VP2 render delegate using the new env variable we have "set MAYAUSD_DISABLE_VP2_RENDER_DELEGATE=1". After setting that env var I launch Maya and in the Output Window I verify that the render delegate is disabled, assure that the pxr usd plugin is enabled and attempt to open InstancerDrawTest.ma in the Outliner I see that cubeModel stage has come in and see in the AE on the instancer that the cube model is assigned as the instanced Geometry. However, I am not seeing it in the viewport. Is it possible for you to test this and see if you can get the instanced geo to show up on your end?

Thank you.

**Comment by wtelford** [comment] 2021-11-22 19:04
Closing this as we can't reproduce it. Please re-open with new repro steps if it remains an issue for you.

**Closed by wtelford** 2021-11-22 19:04 UTC
Labels: bug, vp2renderdelegate
