### ISSUE TITLE
[MAYA-123513] Channel Box: Creating a group and undoing it give Illegal handleUndo() error.

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1951] opened 2022-01-04 21:53 UTC
**Describe the bug**
Creating a group and undoing it with the channel box open, breaks the channel box (where it does not update or draw correctly even after it has been closed and re-opened).

**Steps to reproduce**
1. Open a new file in Maya 2022
2. Navigate to Create -> Universal Scene Description (USD) -> Stage with new layer
3. Right click on the proxy shape -> Add new prim -> Capsule
4. Select the Capsule
5. Press Ctrl+g to create a group
6. Ensure the channel box is visible and that the group the visible object in the channel box
7. Press Ctrl+z to undo creating the group

Notice that the channel box still displays `group1` and selecting other nodes in the outliner does not update it. Selecting a different tab/editor and back to the channel box does not draw the channel box correctly. 

The outliner highlight is also incorrect and it doesn't re-select the grouped objects like native maya. The following line is printed in the terminal:
`std:: Exception in ::notify handler:  Used expired 'Xform' prim </group1> 
`
**Expected behavior**
We would expect the behaviour to be the same as native maya. We would expect it to undo, draw the outliner and re-select the grouped objects.

**Attachments**
![group_undo](https://user-images.githubusercontent.com/12554015/148128286-1624f55e-d871-4222-a067-fd4ec25469ca.gif)

**Specs (if applicable):**
maya2022.update3
Maya Usd: dev at 04f2c94

Pixar Jira MAYA-3186

**Comment by santosd** [comment] 2022-02-07 19:21
Hello @gracekumagai I tested this in a newer build in PR129 and the issue is not visible there. We added some Channel box functionality in the next Maya release and that is where the fix for this will show up.

**Comment by gracekumagai** [comment] 2022-02-08 18:49
Thanks @santosd! Feel free to close out the ticket.

**Comment by gracekumagai** [comment] 2022-02-08 21:19
Hi @santosd, we were wondering if there's a plan to backport the channel box fixes for Maya 2022?

**Comment by santosd** [comment] 2022-02-09 15:40
Hi @gracekumagai, at this time we are not planning on backporting those changes into Maya 2022.

**Comment by santosd** [comment] 2022-05-25 14:25
Thank you! for reporting back and I am glad to hear that you are no longer seeing the error on your end. I am able to reproduce the error on my end I have created a ticket internally MAYA-123513 I will link this GitHub issue to it.

**Comment by santosd** [comment] 2022-05-25 14:26
Going to reopen this for the errors displayed in the Script Editor on undo of the group.

**Comment by santosg87** [comment] 2024-09-16 18:34
this issue has been addressed. although, note that the fix for this required maya changes, so a minimum of Maya2024 is needed for those fixes to be available fully.

closing this for now.

**Closed by santosg87** 2024-09-16 18:34 UTC
Labels: bug
