### ISSUE TITLE
Material names on exported mesh based on shader group instead of material

### ISSUE THREAD

**Issue by stevkalinowski** [Autodesk/maya-usd#506] opened 2020-05-19 23:49 UTC
**Describe the bug**
When I export a mesh to .usd and then import the file back in to Maya, the material names are incorrect.  The shader group names have been used instead and on top of that there is a suffix _lambert one added to the end.

**Steps to reproduce**
* create a mesh sphere
* assign a new blinn material, name it "test_material"
* File > Export All
* File > New
* File > Import, choose the exported usd file
* Notice material name is now "blinn1SG_lambert"

**Expected behavior**
I would expect that the material be named the same as when it was exported.

**Specs (if applicable):**
Windows 10
Maya PR114

**Comment by santosg87** [comment] 2020-05-21 18:16
Thank you for logging this @stevkalinowski 

I can reproduce this on our side as well.

**Comment by JGamache-autodesk** [comment] 2020-05-22 13:32
Not only that, but the material is now a Lambert instead of a Blinn, and all values and connections are lost.

I am looking into improving that, and insights about how much information you expect to transfer losslessly would help. I want, at minimum, to get back a Blinn and having file connections restored.

**Comment by stevkalinowski** [comment] 2020-05-22 15:50
For us maintaining as many file node connections as possible would be expected.  The attribute values would be nice too.

Maybe a stretch, but maybe also the color space setting of the file nodes as well?  sRGB or Raw for example.

**Comment by stevkalinowski** [comment] 2020-05-22 15:55
For clarification, "attribute values" I refer to values alongside the texture inputs, such as eccentricity, diffuse, reflectivity, etc.  Anything in "Common" and "Specular" sections of the attribute editor.  We use lambert, blinn, and phong.

**Comment by stevkalinowski** [comment] 2020-06-25 21:57
If it helps, I've uploaded a sample scene "character_export.zip" to Activision's sharepoint drive.

**Comment by koen-v** [comment] 2021-04-09 21:24
Hello all, was this addressed? If so is there perhaps a CL this was addressed in? In my internal build, I am still getting this, and I was curious where to best start to address it.

Thanks,
Koen

**Comment by JGamache-autodesk** [comment] 2021-04-12 18:39
I would probably start in `UsdMayaShadingModeExportContext::MakeStandardMaterialPrim()` by replacing:
```
        MFnDependencyNode seDepNode(_shadingEngine, &status);
        if (!status) {
            return ret;
        }
        materialName = seDepNode.name().asChar();
```
with
```
        MFnDependencyNode surfDepNode(GetSurfaceShader(), &status);
        if (!status) {
            return ret;
        }
        materialName = surfDepNode.name().asChar();
```
I suspect that is all that would be needed to get the proper material name.

**Comment by koen-v** [comment] 2021-04-12 18:57
Oh, nice, thank you!

**Comment by JGamache-autodesk** [comment] 2021-04-16 15:38
@koen-v Can I have your thoughts on how this will roundtrip?

Seems like the issue is that if you rename "UsdPreviewSurface1" to "myJade" the shading group does not auto-rename to "myJadeSG" so, on export, you end up with a material still having the default name "UsdPreviewSurface1SG" which is not very helpful outside of Maya.

Can I suggest that on import, if we detect that the material name does not end with SG and that the material name matches one of the shader node names that we append with "SG" when creating the shading group?
This would make the first roundtrip lossy, but on a shading group name could be considered stale:
   Maya "UsdPreviewSurface1SG/myJade" becomes USD "myJade/myJade" reimports as Maya "myJadeSG/myJade"
On the second roundtrip, assuming the surface node has not been renamed, we end up with a perfect roundtrip:
   Maya "myJadeSG/myJade" becomes USD "myJade/myJade" reimports as Maya "myJadeSG/myJade"

**Comment by koen-v** [comment] 2021-04-16 16:31
Ah, thanks for bringing this up. For me, the roundtrip is actually a bit different, I often strip most of the materials and keep the GeomSubsets around named after the material. Later, I bind to a material based on this name. That is to mimic the workflow we had when we where storing models in a proprietary format.

In maya, the we have a preview shader that more closely resembles our game shader then the usd preview, so on import we actually rebuild a custom shader and hook it up. Because if this , the name of the geomsubset is crucial for me, while the shading group not so much.

What I would do to roundtrip perfectly, is probably add an attribute to the Material to store the shading group name, although your suggestion is probably better, as the results are pretty much the same, without storing additional data in the usd.

What I have not tried yet, is how the specialized materials round trip. This is related to another question I had, where we get specialized materials in the usd to account for different uv set names. I am not sure how to reconstruct those perfectly. To be honest, I am knee deep in exporting for now, importing is next :)

Cheers,
koen

ps. your suggestion works perfectly.

**Comment by santosg87** [comment] 2021-07-12 20:43
I believe this one is nowfixed on mayaUSD 0.10.0. @koen-v are you able to confirm and close it? thank you!

**Comment by wtelford** [comment] 2021-10-04 18:09
Closing as fixed. Please reopen if your issue persists.

**Closed by wtelford** 2021-10-04 18:09 UTC
Labels: bug, import-export, reproduced

**Comment by koen-v** [comment] 2021-10-04 18:51
Oh, nice, I will try to confirm ( I am a few versions behind at the moment), but thanks for looking at this!
