### ISSUE TITLE
[MAYA-104544] refactoring_sandbox : Adsk Proxy does not draw by default when VP2_RENDER_DELEGATE_PROXY=1 is set

### ISSUE THREAD

**Issue by radon199** [Autodesk/maya-usd#155] opened 2019-12-04 21:11 UTC
Hey,

~~When creating a mayaUsdProxyShape if we first create the shape and then set the filepath the proxy will not draw.~~

~~If we create the proxy and set the path within a single python script the proxy will draw correctly.~~

~~Changing the filepath with a python command or manually on the attribute will not cause the proxy to redraw, however saving the scene and reopening it will cause the proxy to draw whatever is set in it's filepath.~~

**EDIT**
And I figured out the issue as soon as I made a ticket. Due to the segfaults we were having we had set **VP2_RENDER_DELEGATE_PROXY=1** ( which prevented a instant segfault ), but when this is set the proxy will not re-draw when the filepath is set. If we do not enable this env var everything draws as expected. However when not set we lose viewport selection/highlighting and VP2 effects ( as I think this mode now draws the USD proxy with hydra?)

Is anyone seeing this redraw issue when the above env var is set?

CentOs7
Maya-2019.2.8774
maya_usd from 2019/11/29

**Comment by kxl-adsk** [comment] 2019-12-04 21:51
We will be bringing soon changes to trigger viewport refresh when something in UFE/USD changes. I'm not sure if this will be enough since we need to populate hydra after the change of stage.

**Comment by santosg87** [comment] 2020-03-03 14:32
I can reproduce this on our side as well. 

it seems the viewport needs to be refreshed in order to draw. 

one possible workaround here would be to to use the mel command "ogs -reset" to force the update. :)

**Comment by santosg87** [comment] 2020-05-14 13:24
this is now fixed internally and should be available on the next PR :)

**Comment by santosg87** [comment] 2020-06-01 18:52
hi @radon199 this one should be fixed on the latest PR. Would you be able to validate and close it? :)

thank you!

**Comment by kxl-adsk** [comment] 2020-07-16 13:13
I'm closing this issue since the fix was delivered and validated by QA. @radon199 if you find something missing, please reopen or log a new issue.

**Closed by kxl-adsk** 2020-07-16 13:13 UTC
Labels: proxy, question, reproduced, vp2renderdelegate

**Comment by radon199** [comment] 2020-07-31 17:43
Apologies for the massive delay,I was unable to build/work on this for a while. I tested with the latest version and this is working as expected, many thanks.
