### ISSUE TITLE
[MAYA-102530] Unable to select an instance if it is the only instance of a master in VP2

### ISSUE THREAD

**Issue by radon199** [Autodesk/maya-usd#153] opened 2019-12-04 18:22 UTC
Hey,

We tag all references as instanceable in our layouts. This ends up with many masters that may have only a single instance.

I am able to select references with the Adsk Plugin that have at least two instances, but if there is only one ( ie one master and one instance of that master ) I get an warning and the whole proxy is selected.

`Warning: in getInstancedSelectionPath at line 517 of /sw/dev/rousselp/src/MTCR/maya_usd/build/platform-linux/arch-x86_64/os-CentOS-7/boost-1.61.0/python-2.7/maya-2019/maya_usd_stub/usd-19.11.m2/maya_usd/src/maya_usd/lib/render/vp2RenderDelegate/proxyRenderDelegate.cpp -- UFE runtime is not updated for the USD stage. Please save scene and reopen.
`

Reopening the scene does not fix the issue.

**Steps to reproduce :**
1. Open a stage that has a reference that will produce a single master and instance ( ie a Usd Reference that only exists once in the stage but is still tagged as instanceable )
2. Attempt to select this instance with VP2.

**Comment by cfmoore007** [comment] 2019-12-09 21:06
Actually, this seems to be a duplicate of : https://github.com/Autodesk/maya-usd/issues/153

**Comment by cfmoore007** [comment] 2019-12-09 21:08
@radon199 - I may have made a duplicate issue ... Can you confirm if your prims show up in the UFE Outliner in this scenario ?

**Comment by radon199** [comment] 2019-12-09 22:27
Only up to the instanceable prim, everything from the master is hidden.

I wasn’t sure that was relevant because we treat masters that way within our pipeline.

Your issue has more information, except for the fact that viewport selection does work for me with 2 or more instances of the same prim. It is selecting the instanceable prim in this case. 

It should be noted that selecting the instance is the default behavior for usdview/hydra. Usdview however will draw prims under a master to its tree.

**Comment by cfmoore007** [comment] 2019-12-12 13:04
Ok, I'll leave the other issue open then, as it's slightly different.  Thanks for clarifying.

**Comment by HdC-adsk** [comment] 2019-12-12 16:15
It is probably a regression due to the draw performance optimization for single-instanced Rprims.

**Comment by HdC-adsk** [comment] 2019-12-17 22:21
Logged with MAYA-102530.

**Comment by HdC-adsk** [comment] 2020-03-23 19:02
@santosg87 I just tried but failed to reproduce this issue. Can you reproduce it?

**Comment by HdC-adsk** [comment] 2020-04-28 17:49
@santosg87 @santosd Guys, have you been able to reproduce the issue?

**Comment by santosd** [comment] 2020-04-29 19:20
@radon199 I tried to replicate this on my end but wasn't able to on my end. It's possible I am not creating the file correctly. Would you mind attaching a file that I can test this with please. Thank you!

**Comment by santosd** [comment] 2020-05-08 20:34
Hi @radon199 I created a file on my end which I have attached and I was not able to reproduce the warning you are getting on my end and am able to select the one instance. Let me know if the file I attached works for you or not. Tested in both 2020 and PR115. If you have a file to reproduce this with, please let me know.
[tvs_oneInstance.zip](https://github.com/Autodesk/maya-usd/files/4601316/tvs_oneInstance.zip)

**Comment by radon199** [comment] 2020-05-27 18:04
Hi @santosd 

I downloaded your file and it did work, but was still failing with the latest release under dev and our files. I modified your example slightly to include two references to two asset files, both instanceable, and this causes the error and does not select in the viewport for me.

Tested against maya-2020.0.235 and maya-2019.2.8774 ( latest I have of both )

I am unable to include a test file as an attachment due to our security requirements but hopefully this paste of the modifications makes sense. RetroTVB is just a copy and rename of your asset so that USD thinks it's unique.
`#usda 1.0

def "TVs"
{
    def Xform "TV1" (
        instanceable = true
        prepend references = @./RetroTV.usda@</Asset>
    )
    {
        matrix4d xformOp:transform = ( (1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 100, 1) )
        uniform token[] xformOpOrder = ["xformOp:transform"]
    }

    def Xform "TV2" (
        instanceable = true
        prepend references = @./RetroTVB.usda@</Asset>
    )
    {
        matrix4d xformOp:transform = ( (1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, -100, 1) )
        uniform token[] xformOpOrder = ["xformOp:transform"]
    }
}
`

**Comment by santosd** [comment] 2020-05-27 19:32
@radon199, Thank you for sharing the changes you made to the file I sent. I see the error in PR114. However, I don't see the error in PR115. In PR 115 there is another issue though. Selection only selects the body of the TV and when I attempt to move it I get an error at that point.

`Coding Error: in _ValidateEditPrim at line 1270 of S:\jenkins\workspace\ecg-usd-full-windows\ecg-usd-build\usd\pxr\usd\usd\stage.cpp -- Cannot create property spec at path </TVs/TV1/RetroTV/RetroTVBody>; authoring to an instance proxy is not allowed.
Coding Error: in AddXformOp at line 223 of S:\jenkins\workspace\ecg-usd-full-windows\ecg-usd-build\usd\pxr\usd\usdGeom\xformable.cpp -- Unable to add xform op of type TypeTranslate and precision PrecisionDouble on prim at path </TVs/TV1/RetroTV/RetroTVBody>. opSuffix=, isInverseOp=0
Coding Error: in _GetOrAddCommonXformOps at line 867 of S:\jenkins\workspace\ecg-usd-full-windows\ecg-usd-build\usd\pxr\usd\usdGeom\xformCommonAPI.cpp -- Failed verification: ' t '
Coding Error: in _ValidateEditPrim at line 1270 of S:\jenkins\workspace\ecg-usd-full-windows\ecg-usd-build\usd\pxr\usd\usd\stage.cpp -- Cannot create property spec at path </TVs/TV1/RetroTV/RetroTVBody>; authoring to an instance proxy is not allowed.
Coding Error: in _ValidateEditPrim at line 1270 of S:\jenkins\workspace\ecg-usd-full-windows\ecg-usd-build\usd\pxr\usd\usd\stage.cpp -- Cannot create property spec at path </TVs/TV1/RetroTV/RetroTVBody>; authoring to an instance proxy is not allowed.
Runtime Error: in _SetValueImpl at line 5689 of S:\jenkins\workspace\ecg-usd-full-windows\ecg-usd-build\usd\pxr\usd\usd\stage.cpp -- Cannot set attribute value.  Failed to create attribute spec </TVs/TV1/RetroTV/RetroTVBody.xformOpOrder> in layer @anon:000002C15CA4E510:tvs_oneInstance-session.usda@
Coding Error: in _ValidateEditPrim at line 1270 of S:\jenkins\workspace\ecg-usd-full-windows\ecg-usd-build\usd\pxr\usd\usd\stage.cpp -- Cannot create property spec at path </TVs/TV1/RetroTV/RetroTVBody>; authoring to an instance proxy is not allowed.
Coding Error: in AddXformOp at line 223 of S:\jenkins\workspace\ecg-usd-full-windows\ecg-usd-build\usd\pxr\usd\usdGeom\xformable.cpp -- Unable to add xform op of type TypeTranslate and precision PrecisionDouble on prim at path </TVs/TV1/RetroTV/RetroTVBody>. opSuffix=, isInverseOp=0
Coding Error: in _GetOrAddCommonXformOps at line 867 of S:\jenkins\workspace\ecg-usd-full-windows\ecg-usd-build\usd\pxr\usd\usdGeom\xformCommonAPI.cpp -- Failed verification: ' t '
Failed to translate prim |world|Tvs_oneInstance_usd|Tvs_oneInstance_usdShape/TVs/TV1/RetroTV/RetroTVBody - Unable to SetTranslate after conversion to CommonAPI.
	File: S:\Maya_master_DI\src\Maya\src\Components\USD\maya-usd\lib\mayaUsd\ufe\private\Utils.cpp
	Line: 146
	Function: MayaUsd_v0::ufe::translateOp`

It is possible that some of the changes I am seeing on my end are code changes on the Maya side and not just on USD which is why I am seeing slightly different results. I will mark this as reproduced and see if we can get a dev to take a look at it.

**Comment by HdC-adsk** [comment] 2020-05-27 19:41
I guess the issue is still reproducible on Maya 2020?

**Comment by radon199** [comment] 2020-05-27 19:41
I forgot maya-usd can’t handle xform ops yet, that issue will go away if you use transform ops to move the TVs.

I have another issue in for that : https://github.com/Autodesk/maya-usd/issues/157

When is PR115 from? We pulled most recently on the 20th of May.

**Comment by santosd** [comment] 2020-05-27 19:51
I've attached a gif of what I am seeing. In both PR114 and 2020 I am see the warning. However the selection occurs in the viewport and I can translate the object without any issues. In PR115 I can select without warning, but translating causes an error.
![instanceSelectionError](https://user-images.githubusercontent.com/29235905/83065538-a9277b00-a031-11ea-8dd4-3bcf917caf41.gif)

**Comment by radon199** [comment] 2020-05-27 20:15
You’ll notice that in PR114 the whole proxy is selected, which is the behavior when it fails to select the instance. When two are more instances are selected it will properly select just the UFE instance, and will not fall back to selecting the proxy.

However it sounds like it’s a maybe fixed in PR115, I’ll see if I can get a pull of that soon.

On that note I noticed that you are only getting UFE selection and outliner objects for the prim in TV1? What is the expected behavior when selecting sub instanced primitives? Will it select the subcomponent in all instances or will it select the instance root?

**Comment by HdC-adsk** [comment] 2020-05-28 12:21
I believe the single instance selection issue has been fixed for PR115. Please validate.

Except nested instancing case, the expected behavior is to select the extract children prim.

**Comment by radon199** [comment] 2020-05-28 22:52
By the child prim do you mean the child inside the master? Or a virtual child added under the instance similar to UsdInstanceProxy? Looking at santosd’s gif it seems to be selecting child prims under TV1.

If so that’s not the most helpful of behaviors from an artist perspective. When you select an instance you want the instance, not a component of the master. I think before PR115 that was the behavior of the maya usd plugin, or at least the build we have internally, and it’s the behavior we would expect.

I’m having a difficult time finding PR115 on this repo? Is that a Maya release?

**Comment by HdC-adsk** [comment] 2020-07-03 15:40
@radon199 I think what you were suggesting is relevant to selection by kind (#330)?

My latest PR #620 will fix the single instance selection issue for Maya 2020 and before. I will ask you to validate when it is merged.

**Comment by HdC-adsk** [comment] 2020-07-06 18:03
@radon199 PR #620 has been merged. Could you confirm the issue has been fixed?

**Comment by santosd** [comment] 2020-07-14 13:20
I tested on my end that the issue seems fixed. Closing this issue for now.

**Closed by santosd** 2020-07-14 13:20 UTC
Labels: bug, reproduced, vp2renderdelegate

**Comment by radon199** [comment] 2020-07-31 17:50
Sorry for the late reply, I was finally able to build this and try it out and it's all working for me. Thanks.
