### ISSUE TITLE
[MAYA-115171] Outliner not updating with new prim defined in Python

### ISSUE THREAD

**Issue by brycegbrazen** [Autodesk/maya-usd#1808] opened 2021-11-05 03:39 UTC
Describe the bug:

When defining a prim with the USD python API (`stage.DefinePrim('<name_of_prim>'`) and saving the scene. The new prim will not show up in Maya via the Outliner until you reload the layer from disk either with the menu item in the USD Layer Editor (Revert to File) or by running `<layer_name>.Reload()` in the Python API.

- Create a USD Stage with the Create->USD->Stage with New Layer menu item.
- Save the created anonymousLayer to some location on disk.
- Select the stage in Python with the python command: `stage = mayaUsd.ufe.getStage("/<DAG path to the USDProxyShapeNode>")`
- Attempt to define a new prim on the stage with the python command: `stage.DefinePrim("/<a_prim_name>")`
- Save the stage with the python command: `stage.Save()`
- You will notice now that the created prim does not appear in the outliner unless you reload the edited layer from disk. By default this would be the root layer of the stage.

Specs (if applicable):

OS (Windows 10)
Vanilla Maya 2022.1
Pre-installed mayaUSD v0.10.0

**Comment by ecrossno** [comment] 2021-11-15 23:08
I have been having this issue as well. Interested to see a fix for this.

**Closed** 2022-01-31 20:00 UTC
Labels: outliner

**Comment by Ziethriel** [comment] 2023-10-23 17:26
I believe this may have regressed. I am having this problem in Maya 2024.1 with MayaUSD plugin 23.1.

**Comment by marceloserchelihh** [comment] 2024-08-29 20:25
Hi @santosd , I am testing in Maya 2025.1 (Linux Rocky 9.3) with Maya-Usd 0.28.0 and the issue is still there. Could you reopen this ticket?
