### ISSUE TITLE
When deleting a Maya USD node, Maya crashes.

### ISSUE THREAD

**Issue by yujiecong** [Autodesk/maya-usd#3287] opened 2023-08-21 06:25 UTC
**Describe the bug**

**Steps to reproduce**
1. Go to Create
2. Click on Universal Scene Description--> Stage From File
3. Open a usd file
4. delete the usd node on Outliner
5. fetal error and crashed

**Attachments**
Based on my testing, when a USD file has a sublayer that points to an empty USD file, a crash occurs.

this is a first file - test.usda
```
#usda 1.0
(
    defaultPrim = "set"
    subLayers = [
        @./empty.usda@
    ]
)

def "set" (
)
{
}
```
this is a second file - empty.usda
```
#usda 1.0
```

and this is maya crash log
`//=====================================================
Maya Crash Report
//=====================================================

Exception code: 80000003: BREAKPOINT 
Fault address:  18B9B502 in C:\Windows\System32\KERNELBASE.dll
0001:000EA502 Logical offset (see .map file for location)

Call stack:
	Module:  C:\Windows\System32\KERNELBASE.dll (-exported-)
	Location: KERNELBASE.dllDebugBreak + 2 bytes
End of stack

//crash log file name = C:\Users\yanyin\AppData\Local\Temp\MayaCrashLog230821.1358.log
//version     = 24.1.0.4816
//cut            =  04/19/2023, 202304191415
//current scene = unDisclosed
//command history (most recent last):
//====================================================
//last tool: nurbsSelect
//====================================================
//panel with focus: scriptEditorPanel1
//visible panels:
// modelPanel4 outlinerPanel1 scriptEditorPanel1 
//====================================================
//Memory usage:
// 35857.840 Mb	Free Memory
// 32622.082 Mb	Free Swap
// 1186.730 Mb	Current

//====================================================
`

**Specs (if applicable):**
 - Windows 10
 - Maya 2024.1
 - maya usd version 0.23.1

**Comment by santosg87** [comment] 2023-08-22 17:23
hi @yujiecong thanks for logging this issue. I believe this is something we have already fixed on mayaUSD 0.24.0, we had a similar issue logged internally and worked on. are you able to update your plugin to 0.24.0 and give this workflow another try?

I have tried it on my side, and couldn't reproduce this crash on 0.24.0.

cheers!

**Comment by yujiecong** [comment] 2023-08-23 03:26
@santosg87 
You're welcome! I'm glad to hear that your testing went well and the issue is resolved. If you have any more questions in the future, feel free to ask. Thank you again!

**Comment by santosg87** [comment] 2023-08-29 21:26
@yujiecong closing this issue for now. if it is still affecting you, feel free to re-open! :)

**Closed by santosg87** 2023-08-29 21:26 UTC
Labels: bug
